### PR TITLE
Removing uberon:2x never in taxon

### PR DESCRIPTION
**Pull request by shawntanzk**
added command `remove_uberon_two_constraints` that removes all never_in_taxon axioms for uberon:2x and implemented it

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Review by dosumis — APPROVED** [review]
Looks good.  

Not clear to me why this is happening: 

image

@matentzn   - Perhaps some automated redundancy stripping by ROBOT?   Looks harness enough though.

**Comment by shawntanzk** [comment]
@rays22 @dosumis this PR removes all the uberon:2x never in taxon - i have left it unmerge for now in case there are different plans that involve unmerging some things/building on this PR. Happy for it to be merged

**Review by rays22 — APPROVED** [review]
### `uberon-edit.obo`: looks fine
1. The count of the removed taxon constraints in the git diff matches the 1116 cases I expect for `UBERON:2...` classes.
2. Removing the redundant lines like `synonym: "vaginal lumen" EXACT []` for `synonym: "vaginal lumen" EXACT [FMA:19982]` also looks fine.

### `uberon.Makefile`
 I have not tested the updated `uberon.Makefile`, but I noticed that the `select_uberon_two_constraints.sparql` referenced in the code does not exist yet.

**Comment by rays22** [comment]
This pull request is related to https://github.com/obophenotype/uberon/discussions/2158
.

**Pull request merged**
