### PR TITLE
Created general_subset, to replace CARO ontology

### PR DESCRIPTION
**Pull request by balhoff**
Related to #2349

I created a `general_subset` containing terms that must be applicable outside of Metazoa. I'm open to suggestions for an alternative name for the subset. For all these terms, I added present_in_taxon annotations:

- relationship: present_in_taxon NCBITaxon:33090 ! Viridiplantae
- relationship: present_in_taxon NCBITaxon:33208 ! Metazoa
- relationship: present_in_taxon NCBITaxon:4751 ! Fungi

Hopefully these will help catch unwanted taxonomic specificity connected to these terms.

This PR also updates the taxon import to include Fungi.

### CODE REVIEW

**Review by cmungall — APPROVED** [review]
This is great. But should the pr title be edited? This isn’t just the subset. It’s making the conflation commitment! There could Eva lot of knock on changes let’s just make sure this is announced ahead of next release

**Comment by balhoff** [comment]
@cmungall what do you mean by "conflation" in this context? Conflating animal/plant/fungal structures into single classes?

**Comment by matentzn** [comment]
@dosumis will merge this when he is in Berkely mid December.

**Comment by dosumis** [comment]
> @dosumis will merge this when he is in Berkely mid December.

We'll see :)

**Comment by cmungall** [comment]
[it's already accruing conflicts...]

I am in favor of this, we should communicate these plans more broadly though, esp to FAO and PO.

Is the best way to do this to edit the initial comment in #2349 to word more clearly as a specific proposal?

**Comment by dosumis** [comment]
Given the potential for taxonomic scope creep resulting from the newly taxonomically general upper level of Uberon, I've added a suggested taxonomic scope statement to the README.  I think it is important to clearly set expectations.  @balhoff @matentzn  - does this seem reasonable.

**Comment by balhoff** [comment]
Thanks for updating @anitacaron. I will try to make some time to update this PR to change the subset name to `common_anatomy` before merging.

**Comment by balhoff** [comment]
@anitacaron I think this is ready to merge, assuming the tests pass.

**Pull request merged**
