### PR TITLE
issue-1556

### PR DESCRIPTION
**Pull request by bonitalam**

### CODE REVIEW

**Comment by matentzn** [comment]
QC says you actually HAVE to add a cross reference on the definition (`def:`). I cant decipher the system UBERON uses, but I think your ORCID would do (or a doi to the appropriate paper). Here is another example:

```
def: "A spatiotemporal region encompassing some part of the life cycle of an organism." [https://orcid.org/0000-0002-6601-2165]
```

Ok, so I can unfortunately not review this term myself (as I have no idea of biology or medicine), but maybe @wdahdul or @dosumis can help to see whether this is ok. Thanks!

**Comment by bonitalam** [comment]
Thanks for all your help Nico! @matentzn

**Comment by matentzn** [comment]
Always! :) Dont hesitate to ask.

**Comment by cmungall** [comment]
@nicolevasilevsky would you be able to help resolving the conflicts? These arise if a PR is not merged soon enough (sorry!) and it becomes ambiguous how to merge in

**Comment by nicolevasilevsky** [comment]
I will take a look and see if I can fix this

**Comment by nicolevasilevsky** [comment]
Thanks to @ShahimEssaid, we fixed this conflict

**Pull request merged**
