### PR TITLE
depreciating FOVT terms

### PR DESCRIPTION
**Pull request by megbalk**
depreciating more terms:
tip of tail (already exists)
posterior of pes (already exists)
issue #2333

### CODE REVIEW

**Review by nicolevasilevsky — APPROVED** [review]
looks good to me

**Comment by megbalk** [comment]
also added tip of digit. It doesn't look like these were merged?

**Comment by megbalk** [comment]
@nicolevasilevsky it doesn't look like these were merged. Should I redo them?

**Comment by nicolevasilevsky** [comment]
Hm, yeah, it looks like something weird happened, and I'm not familiar enough with GitHub to be able to help. I would just redo it, that would probably be faster.

**Comment by megbalk** [comment]
I see them now!

**Comment by nicolevasilevsky** [comment]
oh good!

**Pull request merged**
