### PR TITLE
add new term UBERON:8000005

### LINKED ISSUE #1570: Henle fiber layer -new term request
Hi,
Can you please add a new term in the Eye Anatomy branch?
Term: Henle fiber Layer 
Synonym: HFL, nerve fiber layer of Henle
Definition: This layer contains bundles of unmyelinated cone and rod photoreceptor axons terminating in the pedicles and spherules that synapse in the retinal outer plexiform layer (OPL).
PMID: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3101665/

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1570

### CODE REVIEW

**Comment by megbalk** [comment]
Need to fix anatomical lines, not ready to merge.

**Comment by nicolevasilevsky** [comment]
@megbalk what needs to be fixed? Can I help?

**Comment by megbalk** [comment]
@nicolevasilevsky thanks for your offer. I will actually close these and start anew as we need to redefine some lines so that they don't have too many parentheses.

**Comment by megbalk** [comment]
@nicolevasilevsky thank you for the offer, but we're going to start anew as we're going to define the anatomical lines differently. 
This pull request will be closed by @ramonawalls

**Comment by ramonawalls** [comment]
Closing

**Comment by cmungall** [comment]
think we are confusing pull requests, so I reopened. I think this can be merged.

This ticket is about #1570 (Henle fiber layer)

The PR about lines is #1586 - this work has already been incorporated into the ontology master branch and will be in the next release! If you think these are wrong please let us know!

As far as I can tell the Henle fiber layer issue and the lines issues are totally unrelated!

**Comment by cmungall** [comment]
@nicolevasilevsky can you confirm - is this PR for henle's layer no longer required?

**Comment by nicolevasilevsky** [comment]
I asked Rama on the ticket. I agree, I think there was a mix up. I'll fix the conflict in the mean time.

**Pull request merged**
