### PR TITLE
adding coracoid process of calcaneus

### PR DESCRIPTION
**Pull request by megbalk**
from issue #2482

### CODE REVIEW

**Comment by megbalk** [comment]
@nicolevasilevsky I'm not sure why this is failing...

**Comment by shawntanzk** [comment]
```
FLAG: relation used but not defined
'http://purl.org/dc/elements/1.1/date' -- property_value: http://purl.org/dc/elements/1.1/date 2022-05-19T21:16:42Z xsd:dateTime

FLAG: relation used but not defined
'http://purl.org/dc/elements/1.1/contributor' -- property_value: http://purl.org/dc/elements/1.1/contributor http://orcid.org/0000-0003-2699-3066
```

These should be dc:terms instead of dc:elements

**Comment by megbalk** [comment]
I think I fixed it...

**Comment by megbalk** [comment]
@nicolevasilevsky can you please review this?

**Review by nicolevasilevsky — APPROVED** [review]
I just fixed the conflict, can you double check that the diff looks correct

**Pull request merged**
