### PR TITLE
Obsolete 'cestode' (UBERON:0018387).

### LINKED ISSUE #1835: UBERON:0018387 cestode
**Uberon term**
UBERON:0018387 cestode

**Reason for deprecation**
"Any of a class (Cestoda) of bilaterally symmetrical flatworms parasitic especially in the intestines of vertebrates. [ http://purl.obolibrary.org/obo/BTO_0005278 ]"
Subclass of larva
This looks incorrect and feels like it should be replaced by NCBITaxon:6199 Cestoda. There's another existing term to represent a cestode larva, though very species-specific: UBERON:0018379 meracestode ("The larval (metacestode) stage of the tapeworm Echinococcus multilocularis. [ http://purl.obolibrary.org/obo/BTO_0000859 ]").  If desired/useful, a broad term for 'cestode larva' could be created in place of 'cestode' to represent any tapeworm larva?

**Suggested replacement or term to consider**
NCBITaxon:6199 Cestoda

Thanks,
Paola

### PR DESCRIPTION
**Pull request by gouttegd**
The term `cestode` (UBERON:0018387) represents a taxon and as such does not belong in Uberon. Obsolete it and propose NCBITaxon:6199 as replacement term.

close #1835

### CODE REVIEW

**Comment by gouttegd** [comment]
@paolaroncaglia If you merely approve a PR, is that already a potential conflict-of-interest?

**Review by paolaroncaglia — COMMENTED** [review]
@gouttegd Thank you for taking care of this. It all looks good to me, but 1) I haven't obsoleted terms in Uberon previously (I'd think it works the same as for other OBO ontologies though) and 2) based on a present discussion elsewhere, I'm not 100% sure if the NCBITaxon class should be entered differently, see https://github.com/obophenotype/uberon/pull/2257#issuecomment-1023144126 and https://github.com/obophenotype/uberon/issues/1904#issuecomment-1023348867

**Comment by paolaroncaglia** [comment]
(The tests to check for correctness of taxon annotations might be inactive at the moment, so just in case...)

**Comment by gouttegd** [comment]
For 1) I am not aware of any Uberon-specific guidelines regarding obsoletion, and I’ve followed what was done in some recent examples of obsoletions in Uberon, so presumably this should be good.

For 2) I did enter the IRI for NCBITaxon:6199 as exemplified in #2257. :) This is why `NCBITaxon:6199` appears in the OBO file as a “naked” identifier and not as a quoted string.

**Review by dosumis — APPROVED** [review]

**Pull request merged**
