### PR TITLE
Release 27 May 2022

### PR DESCRIPTION
**Pull request by matentzn**
Review notes:

- Some EHDAA2 classes removed from base. These are from our `alt_id` cleaning #2486 
- A few hundred human subsets added and present in taxons from #2346 
- A handful of changed MESH ids, presumably from #2432 
- Massive issues with `id: UBERON:0039227` and following, cant merge until @shawntanzk looks into that. No labels, no defs just some axioms. Not just one class.
- A few lost FBBT xrefs (expected)
- One or two added classes. 

At least `id: UBERON:0039227` and following need to be looked into.

### CODE REVIEW

**Comment by shawntanzk** [comment]
This term isnt in edit file, it is coming through vasculature_class.owl which has axioms on it:

```
    <!-- http://purl.obolibrary.org/obo/UBERON_0039227 -->

    <Class rdf:about="http://purl.obolibrary.org/obo/UBERON_0039227">
        <rdfs:subClassOf>
            <Restriction>
                <onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002170"/>
                <someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0001215"/>
            </Restriction>
        </rdfs:subClassOf>
    </Class>
    <Axiom>
        <annotatedSource rdf:resource="http://purl.obolibrary.org/obo/UBERON_0039227"/>
        <annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#subClassOf"/>
        <annotatedTarget>
            <Restriction>
                <onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002170"/>
                <someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0001215"/>
            </Restriction>
        </annotatedTarget>
        <oboInOwl:inSubset rdf:datatype="http://www.w3.org/2001/XMLSchema#string">human_reference_atlas</oboInOwl:inSubset>
    </Axiom>
```

Not 100% sure what is going on but I'm guessing its a mistake from a template? Not sure who to ask in this case.

**Comment by shawntanzk** [comment]
@anitacaron - I see that you have a PR thorugh with vasculature stuff, do you know what the above is?

**Comment by anitacaron** [comment]
Yes, it's related to the HubMap project. The UBERON terms come from the Blood Vasculature ASCT+B table. We expect that all UBERON terms exist, but I'll verify and update the table.

**Comment by shawntanzk** [comment]
@matentzn - this PR https://github.com/obophenotype/uberon/pull/2503 will fix the issue with the uberon term - I'm guessing the release has to be ran again after that gets merged in (waiting for QC to pass). Will you do it or should I? Thanks

**Comment by shawntanzk** [comment]
when running a release with updated stuff, theres a oort error - will try to figure out whats wrong

**Comment by shawntanzk** [comment]
sorry ignore my previous comment, I was on the wrong repo >.< hahaha

**Comment by matentzn** [comment]
Ready for review. When happy, merge; I will take that as a sign I should do a proper release (don't do it manually)

**Pull request merged**
