### PR TITLE
2022-02-16 Release

### PR DESCRIPTION
**Pull request by shawntanzk**
O.M.G. FINALLY! THIS WORKS! 
Will review tmr but just super happy the release ran through!

### CODE REVIEW

**Comment by shawntanzk** [comment]
ROBOT diff too big to comment, ive uploaded them in my google drive here instead: 
https://drive.google.com/drive/folders/1a0bRVDM_rGdY3L3i7wS38O8l5KDW9k_l?usp=sharing

**Comment by shawntanzk** [comment]
Changes: 
- changed creator and contributor to all use dc-contributor with orcid
- removed PNS mutually_spatially_disjoint_with with CNS
**- added never_in_taxon Euarch to feather** -> is there a reason for this? 
-  removed never_in_taxon Teleostei & never_in_taxon Serpentes in lymph node
- Fixed broken images links
- added connected_to relationships to a bunch of vasculature terms (likely related to  changing external pudendal vein tributary_of to connected_to)
- added present_in_taxon mammalian to vermiform appendix
- Edited def of renal column
- Fixed some xref mistakes 
- Edited def of chorion membrane
- added and depracated various synonyms
- Edited def of glomerular visceral epithelium
- Changed glomerular visceral epithelium is_a nephron epithelium to is_a glomerular epithelium
- added never_in_taxon Euarch to exoskeleton
- removed is_a reporductive structure replaced part_of penis with is_a dorsal vein of penis to  deep dorsal vein of penis
- added rostral periventricular region of the third ventricle
- remove part_of epithelial from incisive canal
- merged glomerular visceral epithelium into UBERON:0005751
- added relationship: supplies UBERON:0004176 ! external genitalia to deep external pudendal artery
- added def for pudendal vein
- changed various is_a:anatomical line to is_a: ectoderm-derived structure & is_a: anatomical junction
- obsoleted deep vein of penis
- added rima vulvae
- obsoleted male pudendum
- obsoleted pudendum
- added posterior labial artery
- added urethral artery
- added penile bulb vein
- added urethral vein
- added vestibular bulb vein
- added Alcock's canal
- added superficial dorsal vein of penis
- added dorsal vein of penis
- added dorsal trunk of insect trachea
- added insect trachea
- added rostrum
- added left nasal bone
- addedright nasal bone
- added left zygomatic arch
- added right zygomatic arch
- added antorbital notch
- fixed taxon restrictions that used string to use proper iri
- added HEV as broad abbrv to  high endothelial venule
- added capillary of small intestine
- added lymphoid nodule
- added levatores costarum
- added medullary region of kidney
- added part_of UBERON:0001950 ! neocortex to laminar subdivision of the cortex
- added  rostral periventricular region of the third ventricle
- added xrefs for [Typedef] and fixed various stuff for it

**Comment by shawntanzk** [comment]
Looked through and looks ok, in general only one thing I'm unsure about: - added never_in_taxon Euarch to feather -> is there a reason for this?

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> Looked through and looks ok, in general only one thing I'm unsure about: - added never_in_taxon Euarch to feather -> is there a reason for this?

yes, because they never are :-) but I suppose my edit was technically incorrect based on the new guidelines? If so I'll double-check. Thanks.

**Comment by shawntanzk** [comment]
oh wait! sorry! somehow I wrote it down correctly as added, but in my mind I'm thinking removed LOL, what you get for reviewing it first thing in the morning lol, take my concern back heh

**Pull request closed without merging**
