### PR TITLE
Change external pudendal vein tributary_of to connected_to

### PR DESCRIPTION
**Pull request by shawntanzk**
This seems to be the offending axiom that is causing the unsats
unsats come at tmp/uberon-edit.owl
When this axiom was removed in there, unsats went away. 
@dosumis you mentioned that this is due to over-use of partonomy in representing vasculature -> does that mean removing the axiom is perfectly fine? 
Thanks

### CODE REVIEW

**Comment by anitacaron** [comment]
This is related to #2293

**Review by matentzn — APPROVED** [review]
Let's get @dosumis vote in tho

**Comment by dosumis** [comment]
Suggested fix

[external pudendal vein](http://purl.obolibrary.org/obo/UBERON_0018253) SubClassOf [tributary of](http://purl.obolibrary.org/obo/RO_0002376) some [femoral vein](http://purl.obolibrary.org/obo/UBERON_0001361) [core.owl]
tributary -> connected_to

**Comment by dosumis** [comment]
If that's too much hassle to get release out now, we could keep current fix and resolve later.  It's not such a big deal I think.

**Comment by shawntanzk** [comment]
> [external pudendal vein](http://purl.obolibrary.org/obo/UBERON_0018253) SubClassOf [tributary of](http://purl.obolibrary.org/obo/RO_0002376) some [femoral vein](http://purl.obolibrary.org/obo/UBERON_0001361) [core.owl]

Adding this is in addition to removing `relationship: part_of UBERON:0002103 ! hindlimb` in femoral vein I assume?

**Comment by shawntanzk** [comment]
oh tested it, and i guess you mean instead of removing the relationship

**Comment by shawntanzk** [comment]
Merging this given its @dosumis preference and we were waiting for his input anyway

**Pull request merged**
