### PR TITLE
updated to ODK 1.3.0

### PR DESCRIPTION
**Pull request by shawntanzk**
updated to ODK 1.3.0

### CODE REVIEW

**Comment by matentzn** [comment]
@shawntanzk downt worry about that now, remove all `mirror/*.trigger` in uberon.Makefile to fix the error.

**Comment by shawntanzk** [comment]
error: 

```
Replaced: 27824
Cloning into 'developmental-stage-ontologies'...
cannot open tmp/mirror-emapa.obo at ../scripts/obo-grep.pl line 62.
Killed
make: *** [uberon.Makefile:1053: reports/basic-allcycles] Error 137
```

**Comment by shawntanzk** [comment]
making `tmp/mirror-emapa.obo` locally seems ok

**Comment by matentzn** [comment]
"Killed" means it ran out of memory..

**Comment by shawntanzk** [comment]
is there a fix? do I try manually running it again?

**Comment by matentzn** [comment]
Can you run:

```
ODK_DEBUG=yes ./run.sh make reports/basic-allcycles
```

And share the output?

**Comment by shawntanzk** [comment]
```
2022-02-28 17:57:35,108 ERROR (CommandRunner:4310) Could not find specified ontology http://purl.obolibrary.org/obo/go.owl for --source
Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor.asAxiomSet(SyntacticLocalityModuleExtractor.java:287)
	at uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor.<init>(SyntacticLocalityModuleExtractor.java:282)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4357)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
make: *** [uberon.Makefile:447: imports/go_import.owl] Error 1
Command exited with non-zero status 2
### DEBUG STATS ###
Elapsed time: 9:10.57
Peak memory: 6794836 kb
```

**Comment by matentzn** [comment]
Assign PR to me, no idea what is happening.

**Comment by matentzn** [comment]
```
owltools --use-catalog --no-debug basic.owl --list-cycles -f > reports/basic-allcycles
### DEBUG STATS ###
Elapsed time: 1:06.04
Peak memory: 4320616 kb
```

4.3 GB memory conception, which is somewhat close to the maximum of 6GB.. Not sure yet how to deal with that! Still hoping it was a fluke based on bad weather.

**Review by matentzn — APPROVED** [review]
Looks like it was a fluke! pheeew!

**Pull request merged**
