### PR TITLE
creating cheek tooth row

### PR DESCRIPTION
**Pull request by megbalk**
issue #2617

### CODE REVIEW

**Review by bvarner-ebi — APPROVED** [review]
Consider aligning text definition with logical definition:
An anatomical row consisting of adjacent cheek teeth.
OR
A row of cheek teeth.

**Comment by megbalk** [comment]
@bvarner-ebi I modeled it after "tooth row". Is it preferred to align with previous examples or the logical definition?

**Comment by bvarner-ebi** [comment]
> @bvarner-ebi I modeled it after "tooth row". Is it preferred to align with previous examples or the logical definition?

Ideally both, assuming the previous examples are modelled correctly. I would provide the same feedback for the text definition of 'tooth row'. I was trained to match the text definition with the logical definition. 
If you would like to get more feedback, you could add to the next Uberon call agenda. The text definition does not directly impact reasoning, so it should not cause any conflicts as it is.

**Comment by megbalk** [comment]
@bvarner-ebi @shawntanzk is this ok to merge? It seems not all the checks passed, but I forget which matter.

**Comment by shawntanzk** [comment]
```
 :: ERROR: definition-lacks-dbxref: UBERON:7500114
```
Prob just add your ORCID to it and it will be fine

**Pull request merged**
