### PR TITLE
Replace MeSH tree numbers with unique IDs

### LINKED ISSUE #698: Some MeSH xrefs point to tree locations rather than unique IDs
I have two comments regarding MeSH cross-references:
1. Currently, MeSH xrefs are in terms of tree numbers. For example, the obo file contains `xref: MESH:A01.456.505.733` rather than `xref: MESH:D009666`. A tree number represents a path up the MeSH hierarchy from term to top-level category. Therefore, MeSH terms can have multiple tree numbers, and tree numbers are subject to change whenever the hierarchy is reorganized, even if the term remains. Is there a reason tree numbers are used instead of unique ids? If you would like to switch, you may find my mapping helpful ([notebook](https://github.com/dhimmel/uberon/blob/7de0ed6238c26ea82accae6fc57accd1b845111d/mesh-map.ipynb), [tsv file](https://github.com/dhimmel/uberon/blob/7de0ed6238c26ea82accae6fc57accd1b845111d/data/mesh-map.tsv)).
2. I noticed MeSH mappings only exist for UBERON terms but not terms populated from CL. Since many CL terms contain MeSH terms as citations for the definition (example: `def: "A male germ cell that develops from the haploid secondary spermatocytes. Without further division, spermatids undergo structural changes and give rise to spermatozoa." [MESH:A05.360.490.890.860]`), it appears some of the hard work has already been done. Why are definition sources not included as xrefs and is this the right location to submit CL feature requests?

### PR DESCRIPTION
**Pull request by rays22**
1. Replace MeSH tree numbers with manually mapped unique IDs for the batch of 66 remaining terms.
2.  Delete MeSH tree number xrefs that could not be mapped (as exact match) to unique IDs.
3. Delete secondary MeSH tree number xrefs.

If applied, this commit will fix #698.

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
Hi @rays22, I would like to help review this. Is there a way I can review this other than manually searching and verifying each change>

**Comment by rays22** [comment]
> Hi @rays22, I would like to help review this. Is there a way I can review this other than manually searching and verifying each change?

@bvarner-ebi ,
You can use the [table here](https://github.com/obophenotype/uberon/issues/698#issuecomment-1127548258) that includes human readable labels. You might also pick a subset randomly (e.g. 10) and check those matches more carefully (e.g. if the labels actually match the IDs) if you wish.
I am going to go ahead with merging this pull request, because Shawn has already approved it. In case you found any problematic mappings, just reopen the main ticket with a comment, and I can fix those in another PR.

**Comment by bvarner-ebi** [comment]
Thanks, @rays22. I wasn't able to find the MeSH numbers to validate the old mappings (they did not return results using the [MeSH Browser](https://meshb.nlm.nih.gov/)). 

Regarding the new mappings in the [table](https://github.com/obophenotype/uberon/issues/698#issuecomment-1127548258), they seem reasonable, although some may not be **exact** matches.

E.g.,
radiale - scaphoid bone
ventral thalamus - subthalamus (https://link.springer.com/chapter/10.1007/978-3-540-34686-9_9)
pelvic region of trunk - pelvis

**Comment by shawntanzk** [comment]
> they seem reasonable, although some may not be exact matches.

I think this is a huge problem we've been facing with brain stuff. This is due to many reasons including different groups/atlases defining things differently, spatial vs functional, politics, etc. For these mapping I think it's sensible to push them through as long as they are reasonable for now and refine them as needed. I don't think they mapped as exact in a bridge file from MeSH so don't think anything will break anyway.

**Review by bvarner-ebi — COMMENTED** [review]
Spot checked. Changes seem reasonable.

**Comment by rays22** [comment]
@bvarner-ebi , @shawntanzk ,
Thank you both for checking the mappings and your comments. I agree that some of the MeSH terms may not be an exact match to a given Uberon term, but I think they are reasonably close matches for an xfref, and I doubt that they are worse matches than the ones they replace.
Probably an SSSOM mapping would be a better approach for an alignment than the xrefs.

**Pull request merged**
