### PR TITLE
Add red bone marrow of iliac crest / sternum

### PR DESCRIPTION
**Pull request by paolaroncaglia**
Addresses #2091 and #2092

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@shawntanzk or @matentzn may I ask for your help with the weird diff [here](https://github.com/obophenotype/uberon/pull/2448#issuecomment-1115016695) and the fail, please? I re-run twice. Thank you very much in advance.

**Comment by paolaroncaglia** [comment]
I guess the weird diff is just refactored annotations, but it's the first time I see GitHub-actions output for human view and mouse view - and this is my second PR today, the first one was fine.

**Comment by shawntanzk** [comment]
```
FLAG: relation used but not defined
'http://purl.org/dc/elements/1.1/date' -- property_value: http://purl.org/dc/elements/1.1/date 2022-05-02T13:32:21Z xsd:dateTime
property_value: http://purl.org/dc/elements/1.1/date 2022-05-02T13:39:16Z xsd:dateTime
```

**Comment by shawntanzk** [comment]
We should be using DC:terms instead, see https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit#bookmark=id.bffeg9uviyvz

**Comment by paolaroncaglia** [comment]
@shawntanzk thank you (even more so as it's a bank holiday in the UK). I see that [this](https://github.com/INCATools/ontology-development-kit/issues/587) is still unresolved, so I'll just remove the dates from my 2 new terms (and from my Protege preferences) for now, re-run the PR checks, and merge if successful.

**Comment by paolaroncaglia** [comment]
Nope. I'll close this PR and re-do tomorrow.

**Comment by shawntanzk** [comment]
@paolaroncaglia - it's a different error this time. This time its `killed` so its likely to be a memory issues and tends to resolve if you run the qc checks again.
```
Cloning into 'developmental-stage-ontologies'...
Killed
make: *** [uberon.Makefile:994: reports/basic-allcycles] Error 137
```

**Comment by paolaroncaglia** [comment]
It's taking too long, I'll close and re-do tomorrow.

**Comment by shawntanzk** [comment]
@paolaroncaglia - your QC passed, its all good. Just a heads up, ugur has just implemented an automated diff for subsets, so if that triggers, it takes around 1ish hours to run the whole process (it basically builds the whole uberon).

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> ugur has just implemented an automated diff for subsets, so if that triggers, it takes around 1ish hours to run the whole process (it basically builds the whole uberon).

Ah, thanks for the heads up. I suspect that it would trigger when one creates new terms (mine were clearly applicable to human + mouse subsets), but probably not when say fixing a typo. I'll try again.

**Comment by shawntanzk** [comment]
@paolaroncaglia just another heads up - we are implementing automated diff soon too, so basically all PRs will have a 1ish hour action on it as long as you edit the -edit file. I think if you are working on just minor typos type of fixes, you can ignore that and merge in once the qc check is done.

**Comment by paolaroncaglia** [comment]
@shawntanzk please, qc is fine, but the report has been running for over 2hrs 20' now. I can't see from the log that any process has been killed, so I guess it's still ongoing. I added 2 new terms, so in principle I shouldn't go ahead and merge without waiting, but this is kind of unsustainable if I wish to do any edits this week... may I merge please? :-)

**Comment by matentzn** [comment]
Yes you can merge, assuming you are confident your content is correct :)

**Pull request merged**
