### PR TITLE
add new term 'tooth root apical papilla'

### LINKED ISSUE #3101: NTR: tooth root apical papilla
**Preferred term label:** tooth root apical papilla

**Synonyms**
Exact synonym: 
apical papilla of immature permanent teeth PMID:30834270
apical papilla PMID:18215674

**Definition**
The portion of the dental papilla located at the apex of the root of developing permanent tooth that is responsible for the progressive elongation and maturation of the root. The surface layer is formed by a dense collagen matrix with perpendicular aligned collagen fibers. The inner layer consists of a loosely disorganized collagen matrix with a high concentration of mesenchymal stem cells. Fully mature roots lack apical papilla. 
PMID:18498881 PMID:34026757.

**Parent term**
'is a' tissue (UBERON:0000479)
‘adjacent to' some 'tooth root' (UBERON:0003677)
‘has part’ some 'mesenchymal stem cell' (CL:0000134) 
-> Stem cells from the apical papilla (SCAPs) are a novel population of MSCs residing in the apical papilla of immature permanent teeth (PMID:30834270). TODO

Need some input: 
Does ‘odontogenic papilla’ (UBERON:0001763) apply also to developing permanent tooth? If yes, the requested term “tooth root apical papilla” is a synonym and not a different class.

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-0819-0473

### PR DESCRIPTION
**Pull request by paulacalipho**
fixes #3101

### CODE REVIEW

**Comment by paulacalipho** [comment]
1-	Does ‘odontogenic papilla’ (UBERON:0001763) apply also to developing permanent tooth? 
If yes, the requested term “tooth root apical papilla” is a synonym and not a different class.

2-	The editor comment could be added as part of the definition? 
« The surface layer is formed by a dense collagen matrix with perpendicular aligned collagen fibers. The inner layer consists of a loosely disorganized collagen matrix with a high concentration of mesenchymal stem cells. Fully mature roots lack apical papilla. »
If yes, then the axiom ‘has part’ some 'mesenchymal stem cell' (CL:0000134) could be added.

**Comment by megbalk** [comment]
@paulacalipho it seems that the [linked reference](http://en.wikipedia.org/wiki/Dental_papilla) for odontogenic papilla does not seem unique to a permanent tooth. So I suspect this would need to be a new term.
I would mirror the axioms for [odontogenic papilla](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001763) and add "apical surface" and "part of" some "permanent tooth"

**Comment by paulacalipho** [comment]
Thanks @megbalk for reviewing the term!
 
1. according to PMID:34026757, fully mature root lacks apical papilla (I added this in editor note section). 'part of' some 'permanent tooth', applies only when root are developing. Should I still add it?
2. I do not find the concept 'apical surface' in UBERON
3. Do you think that the editor comment should be added as part of the definition, or I keep it there?

**Comment by megbalk** [comment]
@paulacalipho 
1. perhaps I'm confused on why this term needs to be added. You had asked "Does ‘odontogenic papilla’ (UBERON:0001763) apply also to developing permanent tooth?" Could you clarify why you're asking, I think I assumed it was because the term was needed specifically for a permanent (mature) tooth.
2. you may need to import 'apical surface' from BSPO. 
3. The definition should follow the logical definition. Any additional information should be in the editors note.

**Comment by paulacalipho** [comment]
@megbalk 
1- I am sorry if I was not clear. Once the permanent tooth root is fully mature, the 'apical papilla of the tooth root' disappears. I wanted to confirm whether it is appropriate to add 'part of' some 'permanent tooth' even if the papilla is only present during the maturation of the permanent tooth.
2- OK
3- Sorry again here. I was asking if according to your opinion, what I added in the editor note should be added instead in the definition.

**Comment by megbalk** [comment]
@paulacalipho 
1. Then no, I wouldn't add 'part of' some 'permanent tooth'. Is the 'tooth root apical papilla' specific to something more than the definition of 'odontogenic papilla'?
2. I would keep it as an editor note.

**Comment by paulacalipho** [comment]
@megbalk 
'odontogenic papilla' is defined as a condensation of odontoblast. 
'tooth root apical papilla' is described as containing mesenchymal stem cells (multipotent stem cells of the apical papilla (SCAP) PMID:30834270, PMID:34026757) with high capacity for osteogenic, adipogenic, and chondrogenic differentiation (in vitro).
image

'odontogenic papilla' is definition indicates that it 'gives rise to dentin and pulp in the mature tooth'
'tooth root apical papilla' is described as responsible for the progressive elongation and maturation of the root

**Comment by megbalk** [comment]
@paulacalipho then it seems it is different enough to be its own class and not a synonym, I think.

**Review by megbalk — COMMENTED** [review]
@paulacalipho it looks good but I worry that it won't get nested or be grouped with teeth. Can you add "part of" some "uncondensed odontogenic mesenchyme" and/or "immediate transformation of "tooth root"?

**Comment by paulacalipho** [comment]
@megbalk the term has the relation 'relationship: adjacent_to UBERON:0003677 ! tooth root'. Should be this enough to group it with teeth?
I do not have additional information to add "part of" some "uncondensed odontogenic mesenchyme". Concerning "immediate transformation of" some "tooth root", I would say that "tooth root" is an "immediate transformation of" some "tooth root apical papilla". But again, all the information I have on this term is the one described in the definition and note.

**Review by megbalk — APPROVED** [review]

**Comment by paulacalipho** [comment]
@megbalk Many thanks for reviewing this term

**Pull request merged**
