### PR TITLE
fixes#2394-NTR-developmental_terms

### LINKED ISSUE #2394: NTR: developmental terms
**Comment:** The following terms are needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** aorta gonad mesonephros region
**Synonyms**
aorta-gonad-mesonephros
embryonic aorta gonad mesonephros
**Definition** The aorta-gonad-mesonephros region is an area derived from splanchnopleura mesoderm identified in embryonic humans, mice, and non-mammalian vertebrates such as birds and zebrafish. It contains the dorsal aorta, genital ridges and mesonephros and lies between the notochord and the somatic mesoderm, extending from the umbilicus to the anterior limb bud of the embryo. This region plays an important role in embryonic development, being the first autonomous intra-embryonic site for definitive haematopoiesis. [https://en.wikipedia.org/wiki/Aorta-gonad-mesonephros]
**Parent term** mesoderm UBERON:0000926
**NOTE** derived from splanchnopleure UBERON:0004873
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

**Preferred term label:** ventral presumptive midbrain
**Synonyms** ventral mesencephalon
**Parent term** presumptive midbrain UBERON:0009616
**NOTE** This term will be use to indicate the origin of the cell line: NGC-407 (CVCL_DF59) established from "ventral mesencephalon of a 7-week-old human embryo" PubMed=17555745
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

### PR DESCRIPTION
**Pull request by PaulaDuekRoggli**
fixes #2394 NTR-developmental_terms

### CODE REVIEW

**Review by ANiknejad — CHANGES_REQUESTED** [review]
I am not sure this new class is necessary: if we consider the paper you propose as the motivation for creating this class 'ventral presumptive midbrain', reference PMID:17555745, the authors talk about 'cells derived from the ventral mesencephalon of a 7-week-old human embryo', and I guess, this structure may be covered by UBERON:0001943 midbrain tegmentum
relationship: existence_starts_during_or_after HsapDv:0000024 {gci_relation="part_of", gci_filler="NCBITaxon:9606"} ! CS17
Carnegie stage 17 usually starts between day 42 and day 44 post-fertilization.
see also this link
https://discovery.lifemapsc.com/in-vivo-development/neural-tube/mesencephalic-basal-plate
What do you think, @paulacalipho ?
Also an interesting paper here about midbrain development and cell types detected here https://pubmed.ncbi.nlm.nih.gov/27716510/
(BTW the currently proposed class misses some _is_a_ relationship)

**Comment by paulacalipho** [comment]
Many thanks @ANiknejad for reviewing the term. I thought that UBERON:0001943 midbrain tegmentum was applied to postnatal stage. Where do I find the info about "relationship: existence_starts_during_or_after HsapDv:0000024"? I do not see in  https://www.ebi.ac.uk/ols/index for UBERON:0001943 or in Protege.

**Comment by ANiknejad** [comment]
@paulacalipho 
You will found the relationships describing developmental stages in the composite-metazoan.obo, available here
https://uberon.github.io/downloads.html. I use the .obo file that I open with BBEdit (Mac) or Notepad++ (Windows)

**Comment by paulacalipho** [comment]
@ANiknejad OK, perfect! I found and use the file in the future. So, I will remove this term in the pull request. 
Is the addition of the synonym for the other term (aorta-gonad-mesonephros) OK?

**Comment by ANiknejad** [comment]
I still have to check and will come back soon

**Comment by ANiknejad** [comment]
@paulacalipho 
I understand that you want to add a PMID reference to UBERON:0003105 here below. right?
I am not confortable with the already existing relationship: 'relationship: part_of UBERON:0000947 ! aorta' and I guess, this class needs some check, that you maybe could propose together with the inclusion of the PMID reference, which seems to be correct as fas as I understand.

[Term]
id: UBERON:0003105
name: dorsal lateral plate region
namespace: uberon
def: "Region located near the pronephros and pronephric ducts that is a site of hematopoiesis in the embryo." [http://www.ncbi.nlm.nih.gov/pubmed/9618755, ZFIN:curator]
subset: efo_slim
subset: uberon_slim
synonym: "AGM region" RELATED [XAO:0003051]
synonym: "aorta-gonads-mesonephros region" RELATED [XAO:0003051]
synonym: "DLP" EXACT [XAO:0003051]
xref: AAO:0011008
xref: XAO:0003051
is_a: UBERON:0004120 ! mesoderm-derived structure
is_a: UBERON:0005291 ! embryonic tissue
relationship: existence_starts_during_or_after XAO:1000023 {gci_relation="part_of", gci_filler="NCBITaxon:8353"} ! NF stage 13 (Xenopus)
**relationship: part_of UBERON:0000947 ! aorta**
relationship: part_of UBERON:0002390 {source="XAO"} ! hematopoietic system
relationship: part_of UBERON:0003081 {source="XAO"} ! lateral plate mesoderm
property_value: external_definition "Region located near the pronephros and pronephric ducts that is a site of hematopoiesis in the embryo.[AAO]" xsd:string {date_retrieved="2012-06-20", external_class="AAO:0011008", ontology="AAO", source="AAO:EJS"}
property_value: external_definition "Region where blood progenitor markers are expressed. Probable site of definitive hematopoiesis between 36hpf and 4dpf.[TAO]" xsd:string {date_retrieved="2012-08-14", external_class="TAO:0005028", ontology="TAO", source="ZFIN:curator"}

Another closely related UBERON class (UBERON:0018549) exists, dedicated to zebrafish hematopoiesis

[Term]
id: UBERON:0018549
name: ventral wall of dorsal aorta
namespace: uberon
def: "Region where blood progenitor markers are expressed. Probable site of definitive hematopoiesis between 36hpf and 4dpf." [ZFA:0005028, ZFA:curator]
synonym: "AGM" RELATED [ZFA:0005028]
synonym: "aorta gonad mesonephros region" RELATED [ZFA:0005028]
synonym: "DA roof" RELATED [ZFA:0005028]
synonym: "DA-PCV joint" EXACT [ZFA:0005028]
synonym: "DA-PCV joint" NARROW [ZFA:0005028]
synonym: "dorsal aorta - posterior cardinal vein joint" EXACT [ZFIN:ZDB-PUB-061227-29]
synonym: "DP joint" RELATED [ZFA:0005028]
xref: EFO:0003699
xref: TAO:0005028
xref: ZFA:0005028
is_a: UBERON:0000479 {source="ZFA"} ! simple tissue
is_a: UBERON:0004120 ! mesoderm-derived structure
relationship: existence_ends_during_or_before ZFS:0000044 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! Adult
relationship: existence_starts_during_or_after ZFS:0000028 {gci_relation="part_of", gci_filler="NCBITaxon:7954"} ! Segmentation:26+ somites
relationship: part_of UBERON:0002390 {source="ZFA"} ! hematopoietic system
relationship: part_of UBERON:0005805 {source="ZFA"} ! dorsal aorta

this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5825844/
helps to clarify 'AGM in mammals (mouse):
'The AGM is an embryonic tissue derived from the mesodermal germ layer that contains the dorsal aorta, the genital ridge (which gives rise to the gonads), and the mesonephros (which gives rise to the kidneys), and that extends from the anterior limbs to the posterior limbs of the E9.5 to E12.5 mouse embryo (Fig. 1A) ([de Bruijn et al., 2000](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5825844/#DEV139691C33); [Medvinsky et al., 2011](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5825844/#DEV139691C77)).'

**Comment by paulacalipho** [comment]
@cmungall: I removed the requested term "ventral presumptive midbrain" UBERON:8480036 because I can use "midbrain tegmentum" UBERON:0001943

@cmungall: I added the synonym: aorta-gonad-mesonephros to UBERON:0003105 with PMID:16480451 as reference. This led me to review the definition and relationship of this term and of "ventral wall of dorsal aorta" UBERON:0018549.
Anne Niknejad suggested me to review these terms with you. I think these terms could be improved. I made some suggestions but I lack expertise here. For the purposes of Cellosaurus mapping, we can use this term without modification.

**Review by cmungall — APPROVED** [review]

**Pull request merged**
