### PR TITLE
Fixes #3317 Fallopian tube hierarchy and relabel

### LINKED ISSUE #3317: Revise subclasses of 'subdivision of oviduct'
Exploring CL, we have found that there are cell types from endometrium and vagina that wrongly classified as part_of fallopian tube. This is caused as oviduct in Uberon comprises from the ovaries until the exterior of the body:

> A tube or collection of tubes in an animal from the ovaries to the outside of the body.

Therefore, uterus and vagina are 'subdivision of oviduct. However, the logical definition of 'fallopian tube' is:

` 'subdivision of oviduct' and ('part of' some oviduct) and ('develops from' some 'Mullerian duct')`

The uterus and the upper part of the vagina develop from the 'Mullerian duct' (although in Uberon only 'upper part of vagina' contains the axiom), resulting in being classified as part of the 'fallopian tube'.

Therefore, the logical definition of 'fallopian tube' should be removed.

Moreover, 'oviduct epithelium' is part_of the 'fallopian tube'. This should be the opposite in agreement with the current definitions of oviduct and fallopian tube.

cc @cmungall what do you think of these proposed changes?  For reference, I think you added this editor note to oviduct:

> sometimes oviduct is used interchangeably with follaopian tube. Here they are different - the oviduct connects the gonad to the outside in a variety of animals. The mammal-class fallopian tube is derived from the mullerian duct and connects the gonads/infubdibulum to the uterus

### PR DESCRIPTION
**Pull request by aleixpuigb**
Fixes #3317 Fallopian tube hierarchy and relabel
- 'Fallopian tube' EquivalentTo has been removed, and axioms are now Subclasses.
- it has been removed 'oviduct epithelium' SubclassOf 'part of' some 'Fallopian tube', since Fallopian tube is part_of an oviduct.
- Relabels 11 structures that are 'part of' some 'fallopian tube' from 'X of uterine tube' to 'X of Fallopian tube'
- During relabeling it was obvious that `placental caruncle` was using 'mucosa of uterine tube' as 'mucosa of uterus', a term that doesn't exist. Therefore, it has been ammended to 'located in' some uterus, and it will be evaluated if 'mucosa of uterus' should be added.

### CODE REVIEW

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by aleixpuigb** [comment]
All the structures that are no longer [mesoderm-derived structure](http://purl.obolibrary.org/obo/UBERON_0004120) should be solved adding uterus SubclassOf 'develops from' some 'Mullerian duct'.

**Comment by Caroline-99** [comment]
I would suggest changing `"ampulla of uterine tube"` to `"ampulla of fallopian tube"` for consistency

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Review by Caroline-99 — APPROVED** [review]

**Pull request merged**
