### PR TITLE
Replace type definition for plural form synonyms

### LINKED ISSUE #3058: Add OMO import to UBERON
Context: https://github.com/obophenotype/cell-ontology/issues/2045

Depends on importing OMO (@anitacaron).

Once OMO is imported, edit all plural term annotation properties to [OMO:0003004](http://purl.obolibrary.org/obo/OMO_0003004) 'plural form'.

### LINKED ISSUE #3080: Standardise annotation property: 'plural form' (UBERON)
**Related issue:** https://github.com/obophenotype/cell-ontology/issues/2045
**Depends on/Prerequisite:** OMO import added to UBERON

Uberon currently has at least four versions of the annotation property concept 'plural term':

-http://purl.obolibrary.org/obo/uberon#PLURAL

-http://purl.obolibrary.org/obo/uberon/core#PLURAL

-http://purl.obolibrary.org/obo/cl#PLURAL

-http://purl.obolibrary.org/obo/caloha-reqs-vetted#PLURAL

As part of an effort to standardise synonym_type_properties in OBO ontologies (like https://github.com/obophenotype/cell-ontology/pull/2143), this ticket proposes to delete the above annotation properties and replace all with the OMO term [OMO:0003004 'plural form'](http://purl.obolibrary.org/obo/OMO_0003004).

This ticket will address native instances of the property in UBERON.
A separate PR addresses native instances in CL: https://github.com/obophenotype/cell-ontology/pull/2143.

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #3080 by replacing the ad-hod "plural" synonym type definition with the equivalent, externally defined OMO:0003004

## Depends on

- [x] https://github.com/obophenotype/uberon/pull/3087
- [x] https://github.com/obophenotype/uberon/issues/3058
- [x] https://github.com/obophenotype/uberon/pull/3092

### CODE REVIEW

**Comment by anitacaron** [comment]
Wait for #3087 to be merged.

**Comment by anitacaron** [comment]
Also, it needs to wait for #3058

**Comment by cthoyt** [comment]
Can you please point me towards the file that is the "core" document?

**Comment by anitacaron** [comment]
Actually, you missed one term:

```
[Term]
id: UBERON:0008874
name: pulmonary acinus
def: "The largest lung subunit in which all airways participate in gas exchange, and it is composed of the parenchyma of the respiratory bronchioles, alveolar ducts, and alveoli." [MP:0010911, PMID:2014492, PMID:3382030, Wikipedia:Acinus#The_Lungs]
subset: pheno_slim
synonym: "acinus pulmonaris" EXACT LATIN [FMA:7313, FMA:TA]
synonym: "arbor alveolaris" EXACT LATIN [FMA:7313, FMA:TA]
>>synonym: "pulmonary acini" EXACT PLURAL [PMID:37025383]<<
```

**Comment by cthoyt** [comment]
@anitacaron fixed in a2576a4

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
