### PR TITLE
Addresses #2644 Question on anatomical modelling of 'dorsal root ganglion' and 'spinal nerve root' 

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #2644 Question on anatomical modelling of 'dorsal root ganglion' and 'spinal nerve root'

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
@shawntanzk, it doesn't look like QC checks have ran / are running. Have they been disabled?

**Comment by shawntanzk** [comment]
> @shawntanzk, it doesn't look like QC checks have ran / are running. Have they been disabled?

It's running - sometimes you have to refresh your page

**Comment by shawntanzk** [comment]
could you put a comment or something on what we discussed, or if you prefer, write it down in a ticket and use seealso and point it to the ticket. Thanks :)

**Comment by shawntanzk** [comment]
oh wait i see theres already a ticket, add discussion there and add seealso pointing there then. Thanks!

**Comment by bvarner-ebi** [comment]
> oh wait i see theres already a ticket, add discussion there and add seealso pointing there then. Thanks!

Is it standard to add a seealso annotation when fixing incorrect modelling?
I understand doing that for controversial edits, but this edit seems to fix a seemingly obvious mistake.

**Comment by shawntanzk** [comment]
its not so much the obvious mistake, its the lack of putting any replacement located_in that would be good to have an explanation for

**Review by cmungall — APPROVED** [review]

**Pull request merged**
