### PR TITLE
adding anatomical lines and points for terms needed for traits

### PR DESCRIPTION
**Pull request by megbalk**
molar and premolar tooth
hind foot anatomical lines
body anatomical lines
points on the humerus and lines along the humerus
points on the femur and lines along the femur

### CODE REVIEW

**Comment by cmungall** [comment]
Hi @megbalk !

It looks like your PR failed because your definitions are not attributed.

The reporting is a little opaque, sorry:

https://travis-ci.org/github/obophenotype/uberon/builds/681269934#L219-L245

'definition-dbxref' is an annotation on the definition assertion (in Protege/OWL terms). We like all definitions to have provenance. You can use a definitive source (e.g. DOI), or you can just use your orcid. Let me know if you need more instructions

**Comment by megbalk** [comment]
@cmungall I see an annotation "definition" and "database_cross_reference" but not "definition-dbxref". Which should I use?

**Comment by nicolevasilevsky** [comment]
@megbalk I can answer this question. You need to add a database_cross_reference annotation to your definition, for example:

image
(this example is UBERON_0006983 'anatomical point')

- To do this, on your term, click on the @ symbol next to your definition on the term you added:
image

- A new box will open and click the grey plus button next to Annotations
image

- Select database_cross_reference on the left hand menu, and add your dbxref in the text box
image

- click OK

**Comment by megbalk** [comment]
@nicolevasilevsky thank you!

**Comment by cmungall** [comment]
I'm not sure why the git conflict arose - this wasn't your fault

anyway I moving your changes to another PR as this is the easiest way to fix: #1592 

I have a few additional requests I made a new ticket: #1593

**Pull request closed without merging**
