### PR TITLE
Fix the check for taxon constraint violations

### PR DESCRIPTION
**Pull request by gouttegd**
Since last November, we normally have a check in place to automatically detect any violations of the taxon constraints set forth in the ontology.

Unfortunately, since we migrated to ODK 1.5 back in March, that check has been neutered. This is because the ODK 1.5 defaults to stripping most annotation properties from the imported modules. One of the properties that ended up being stripped is `OMO:0002000` (“defined by construct”), which is used by ROBOT‘s [expand](https://robot.obolibrary.org/expand) command to inject constructed axioms into the ontology wherever the annotation is used. In particular, the expansion of `RO:0002175` (“present in taxon“) is a critical step in the aforementioned check for violations of taxon constraints. Without that property, `RO:0002175` is, in effect, meaningless, and we cannot enforce any constraint that depends on it.

This PR updates the ODK configuration to stop it from stripping the `OMO:0002000` annotation property when refreshing the imports, thereby restoring the enforcement of taxon constraints.

My sincerest apologies to the Uberon community for having missed that issue not once, but twice: when we implemented the annotation stripping in ODK 1.5 and when we first updated the imports here after the 1.5 migration.

### CODE REVIEW

**Comment by gouttegd** [comment]
Unfortunately, in the 6 months since we did not have a functioning TC violations check, TC violations did find their way in the ontology.

First one:

* [red pulp of spleen](http://purl.obolibrary.org/obo/UBERON_0001250) is [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Danio rerio](http://purl.obolibrary.org/obo/NCBITaxon_7955)
* but [red pulp of spleen](http://purl.obolibrary.org/obo/UBERON_0001250) is (indirectly, summarising the hierarchy here) [part of](http://obolibrary.org/obo/BFO_0000050) some [spleen](http://purl.obolibrary.org/obo/UBERON_0002106)
* which [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [spleen primordium](http://purl.obolibrary.org/obo/UBERON_0006293)
* which is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [dorsal mesogastrium](http://purl.obolibrary.org/obo/UBERON_0005602)
* which is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [mesentery of stomach](http://purl.obolibrary.org/obo/UBERON_0003281)
* which [is part of](http://purl.obolibrary.org/obo/BFO_0000050) some [stomach](http://purl.obolibrary.org/obo/UBERON_0000945)
* which is [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) some [Danio rerio](http://purl.obolibrary.org/obo/NCBITaxon_7955)

Possible fix: Removing the following axiom:

> [spleen primordium](http://purl.obolibrary.org/obo/UBERON_0006293) [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [dorsal mesogastrium](http://purl.obolibrary.org/obo/UBERON_0005602)

Without knowing much about the development of the spleen, it seems like a bold claim to state that the spleen primordium is always part of the dorsal mesogastrium, in any species where a spleen (and therefore a spleen primordium) exists.

**Comment by gouttegd** [comment]
Next violation:

* [vertebra cartilage element](http://purl.obolibrary.org/obo/UBERON_0011094) is [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Eptatretus burgeri](http://purl.obolibrary.org/obo/RO_0002161) (inshore hagfish)
* but it [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [vertebra pre-cartilage condensation](http://purl.obolibrary.org/obo/UBERON_0011095)
* which [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) some [vertebra](http://purl.obolibrary.org/obo/UBERON_0002412)
* which is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [vertebral column](http://purl.obolibrary.org/obo/UBERON_0001130)
* which is [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) some [Myxinidae](http://purl.obolibrary.org/obo/NCBITaxon_7762) (hagfishes)

Here I am skeptical about that property chain:

> [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

Just because a “vertebra cartilage element“ _may_ develop into a vertebra should not necessarily imply, I believe, that said elements can only exist in taxon where vertebrae exist.

That chain does not exist in upstream RO, it is explicitly added in Uberon:

```
[Typedef]
id: in_taxon
name: in taxon
xref: RO:0002162
holds_over_chain: has_potential_to_develop_into in_taxon
```

@balhoff @cmungall Thoughts?

**Comment by gouttegd** [comment]
The last one has its cause in CL, I believe.

* [placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) is [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)
* but it is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005)
* which is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [placenta labyrinth](http://purl.obolibrary.org/obo/UBERON_0003946)
* which is [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)

According to the taxon notes on [placenta labyrinth](http://purl.obolibrary.org/obo/UBERON_0003946), Uberon is correct here, so one of the CL assertions is wrong:

* either those cells should not be part of some [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005)
* or they should not be [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606)

**Comment by matentzn** [comment]
I am very sorry to have caused this - my mental reasoner should have been alert when answering the question: are there Annotation Properties that are needed for _logical reasoning_ - as `AP != logic` was so ingrained in my mind it didnt make the leap.

**Comment by anitacaron** [comment]
It seems the taxon constraint QC is still not working in the GitHub Action. Shouldn't this PR fail?

**Comment by gouttegd** [comment]
> It seems the taxon constraint QC is still not working in the GitHub Action. Shouldn't this PR fail and post the comment with the violations?

Indeed. There are other problems than the non-expansion of OMO:0002000, I am looking into it (I am doing some tests in #3337). From what I can tell for now, there are at least two more problems:

* The violations I highlighted above (that I found by running the check locally on my machine with ROBOT 1.9.6) are _not_ caught by ROBOT 1.9.5 (probably because 1.9.5 uses ELK 0.5 while 1.9.6 uses ELK 0.6). The CI check is done with ODK 1.5 which still uses ROBOT 1.9.5 (1.9.6 was not released yet when we put ODK 1.5 out back in March), so that alone is enough to explain why the CI check passes on this PR.

* But even then, when running the test suite with ODK 1.5.2 (which includes ROBOT 1.9.6), the violations _are_ caught ([see log](https://github.com/obophenotype/uberon/actions/runs/10379260790/job/28737117979?pr=3337), but the workflow somehow does not fail. I am currently at a loss understanding why that is the case.

**Comment by gouttegd** [comment]
> But even then, when running the test suite with ODK 1.5.2 (which includes ROBOT 1.9.6), the violations are caught ([see log](https://github.com/obophenotype/uberon/actions/runs/10379260790/job/28737117979?pr=3337), but the workflow somehow does not fail. I am currently at a loss understanding why that is the case.

OK, that was a false problem, just a side effect of one of the changes I made in #3337 for testing.

So, the TC check now (with this PR) is, in fact, working again, it’s just that the ODK 1.5 that we use in CI doesn’t catch what ODK 1.5.2 is catching.

@anitacaron @matentzn Any objection to switch to ODK 1.5.2 in Uberon QC? Presumably Anita does the releases with 1.5.2 anyway, so it’d make sense to use 1.5.2 in QC as well.

**Comment by balhoff** [comment]
> Next violation:
> 
> * [vertebra cartilage element](http://purl.obolibrary.org/obo/UBERON_0011094) is [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Eptatretus burgeri](http://purl.obolibrary.org/obo/RO_0002161) (inshore hagfish)
> * but it [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [vertebra pre-cartilage condensation](http://purl.obolibrary.org/obo/UBERON_0011095)
> * which [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) some [vertebra](http://purl.obolibrary.org/obo/UBERON_0002412)
> * which is [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [vertebral column](http://purl.obolibrary.org/obo/UBERON_0001130)
> * which is [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) some [Myxinidae](http://purl.obolibrary.org/obo/NCBITaxon_7762) (hagfishes)
> 
> Here I am skeptical about that property chain:
> 
> > [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
> 
> Just because a “vertebra cartilage element“ _may_ develop into a vertebra should not necessarily imply, I believe, that such elements can only exist in taxa where vertebrae exist.
> 
> That chain does not exist in upstream RO, it is explicitly added in Uberon:
> 
> ```
> [Typedef]
> id: in_taxon
> name: in taxon
> xref: RO:0002162
> holds_over_chain: has_potential_to_develop_into in_taxon
> ```
> 
> @balhoff @cmungall Thoughts?

I'm not sure, but @wdahdul may also have an opinion about this.

**Comment by gouttegd** [comment]
The unsat involving CL’s [placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) has been fixed CL and a CL release with the fix is already available, so that particular issue will be automatically fixed in Uberon the next time we’ll refresh the imports.

As for the issue with the [vertebra cartilage element](http://purl.obolibrary.org/obo/UBERON_0011094) (see [comment](https://github.com/obophenotype/uberon/pull/3336#issuecomment-2287042250)), editors at the Uberon call of August 19th, 2024 agreed with the proposed removal of the property chain:

> [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

I plan to proceed with said removal unless someone objects to it in the next 3 weeks.

**Comment by cmungall** [comment]
Keep the property chain. You can make an RO ticket for me to clarify the relation. Think of it as being there is genetic programming to make A develop into B. It is stronger than "may" (mays-as-existentials-considered-harmful). 

The fix is to change the individual relationship to potential to develop into some UBERON:0010913 ! vertebral element.

**Comment by gouttegd** [comment]
> Keep the property chain. You can make an RO ticket for me to clarify the relation.

Will do.

But if the property chain is correct, I believe it should belong in RO – that is, the property chain should still be removed from here and added to RO instead.

**Comment by gouttegd** [comment]
> > The fix is to change the individual relationship to potential to develop into some UBERON:0010913 ! vertebral element.

There are two `has_potential_to_develop_into` relationships involved here:

* 'vertebra cartilage element' `has_potential_to_develop_into` some 'vertebra' (1)
* 'vertebra pre-cartilage condensation' `has_potential_to_develop_into` some 'vertebra' (2)

Any of the two is enough to make 'vertebra cartilage element' (which is `present_in_taxon` some 'Eptatretus burgeri') unsatisfiable, because they both link it (through 'vertebra') to 'vertebral column' (which is `never_in_taxon` some Myxinidae).

Changing both of these relationships to `has_potential_to_develop_into` some 'vertebral element' (as proposed) would indeed “fix” the unsat but I am not sure it would make much sense, because both 'vertebral cartilage element' and 'vertebra pre-cartilage condensation' _are_ 'vertebral element' (they are both logically defined as “'vertebral element' that...”). So we would end up saying that something that is a 'vertebral element' `has_potential_to_develop_into` some 'vertebral element'.

So what I propose to do instead:

* remove relationship (1) above entirely;
* change relationship (2) into

> 'vertebra pre-cartilage condensation' `has_potential_to_develop_into` some 'vertebra cartilage element'

That is, we would go this (current hierarchy)

* 'vertebral element'
  * 'vertebra pre-cartilage condensation'
    * `has_potential_to_develop_into` some 'vertebra'
  * 'vertebra cartilage element'
    * `develops_from` some 'vertebra pre-cartilage condensation'
    * `has_potential_to_develop_into` some 'vertebra'
  * 'vertebra'
    * `develops_from` some 'vertebra cartilage element'

to this:

* 'vertebral element'
  * 'vertebra pre-cartilage condensation'
    * `has_potential_to_develop_into` some 'vertebra cartilage element'
  * 'vertebra cartilage element'
    * `develops_from` some 'vertebra pre-cartilage condensation`
  * 'vertebra'
    * `develops_from` some 'vertebra cartilage element'

**Review by balhoff — APPROVED** [review]

**Pull request merged**
