### PR TITLE
Replace type definition for dubious synonyms

### PR DESCRIPTION
**Pull request by cthoyt**
This PR demonstrates replacing the *ad hoc* synonym type definition inside UBERON for dubious/contested synonyms with standard ones from OMO.

The diff is relatively small, but if there are no issues with this, I can easily extend it to the definitions for `ABBREVIATION`, `DEPRECATED`, `MISSPELLING`, and `PLURAL`.

## Depends on

- [x] https://github.com/obophenotype/uberon/pull/3087
- [x] https://github.com/obophenotype/uberon/issues/3058
- [x] https://github.com/obophenotype/uberon/pull/3092

### CODE REVIEW

**Comment by uberon** [comment]
This is great, thanks. Yes, the other types would be useful too

**Comment by cthoyt** [comment]
@uberon I can do them all in this PR or we can do it in an incremental way, what's your preference?

**Comment by anitacaron** [comment]
Sorry, this needs to be moved to the next release because I didn't import OMO:0003002 previously, and I don't have much more time to run the release today.

**Review by cmungall — DISMISSED** [review]

**Comment by anitacaron** [comment]
Still need to import OMO:0003002 here

**Comment by cthoyt** [comment]
@anitacaron I added the appropriate OMO import

**Comment by anitacaron** [comment]
I'm updating `merged_import.owl` file.

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
