### PR TITLE
Revert "depreciating FOVT terms"

### PR DESCRIPTION
**Pull request by megbalk**
Reverts obophenotype/uberon#2457

### CODE REVIEW

**Comment by megbalk** [comment]
@nicolevasilevsky sorry, I merged thinking everything passed. I just reverted and am fixing the issues.

**Comment by shawntanzk** [comment]
I'm guessing, this is no longer needed with the other PR? if so could you help close it please @megbalk thanks :)

**Comment by megbalk** [comment]
@shawntanzk close this PR or the [other one](https://github.com/obophenotype/uberon/pull/2463#issuecomment-1120936800)?

**Comment by shawntanzk** [comment]
> @shawntanzk close this PR or the [other one](https://github.com/obophenotype/uberon/pull/2463#issuecomment-1120936800)?

This PR is just to revert the changes, but instead you are going to try to fix them no? either way, happy for you to leave them open if need be, was just doing a bit of cleaning up in uberon the other day :)

**Comment by megbalk** [comment]
@shawntanzk has the reversion been done? I am a little confused how this process works

**Comment by shawntanzk** [comment]
> @shawntanzk has the reversion been done? I am a little confused how this process works

nope, this pull request has got to be merged before the terms are unobsoleted

**Comment by megbalk** [comment]
@shawntanzk then can I get some help?

**Comment by shawntanzk** [comment]
```
 :: ERROR: definition-lacks-dbxref: UBERON:7500035
  :: ERROR: definition-lacks-dbxref: UBERON:7500039
  :: ERROR: logic-axiom-references-obsolete: UBERON:7500039 has relationship to https://orcid.org/0000-0003-2699-3066
  :: ERROR: logic-axiom-references-obsolete: UBERON:7500035 has relationship to https://orcid.org/0000-0003-2699-3066
```

Seems like reverting results in the same error, not sure what is going on here :( super strange. I don't think you should revert then, rather we should see if we can fix the terms you deprecated.

**Comment by shawntanzk** [comment]
I'll push this to the tech board and hope we can fix it soon but I am not sure how to handle.

Summary for techboard (@anitacaron - could you bring this up on Monday, I'll be away)
1) Currently qc passes, but robot cannot build with the error message above
2) removing the ORCID causes qc to fail (lacking dbxref on def - should we consider changing this check to exclude obsolete?)
3) changing contributor to def xref results in the above fail still

**Pull request closed without merging**
