### PR TITLE
Remove calf synonyms from UBERON:0003823. Create 3 new terms: calf, skin of calf and front hindlimb zeugopod

### LINKED ISSUE #2638: skin of calf
**Uberon term** lower leg skin UBERON:0004264

**Synonym to be added** skin of calf; calf skin

**broad/exact/narrow/related ?** narrow

**Comment**: 
Calf is the back of the lower leg. Calf appears in UBERON as narrow synonym of hindlimb zeugopod UBERON:0003823. I do not know what is best:
1- create term calf and remove it from narrow synonym of hindlimb zeugopod UBERON:0003823, and then create calf skin
2- add calf skin to lower leg skin UBERON:0004264.
I think 1 is more correct, but let you decide, thanks

### PR DESCRIPTION
**Pull request by paulacalipho**
fixes #2638

Anita edit: This PR also normalise the edit file to Protégé 5.6.1

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Oh good, things seem to be working!

Btw, I updated the instructions on how to increase your memory in Protege 5.6.1:
https://github.com/OBOAcademy/obook/blob/master/docs/howto/set-up-protege.md

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
There are conflicts, @paulacalipho can you fix them? thanks!

**Comment by anitacaron** [comment]
I can fix it.

**Comment by paulacalipho** [comment]
@nicolevasilevsky @anitacaron Many thanks to both of you!

**Comment by paulacalipho** [comment]
@nicolevasilevsky I was working with Protege 5.5, updated to 5.6 and worked. thanks for your help

**Comment by anitacaron** [comment]
@nicolevasilevsky, following the instructions to increase the memory in Protégé 5.6. The file to set the memory is inside the config folder, the `jvm.conf` file. It's a bit different for me, or it seems incomplete in the instructions. Isn't it the same in your case?

**Comment by nicolevasilevsky** [comment]
Hey @anitacaron- yes, looks like the process is different to increase the memory in Protege 5.6.1, I updated the instructions here:
https://oboacademy.github.io/obook/howto/set-up-protege/

(I realize that this entire document should be updated for the new version, I'll work on it when I have a chance.)

**Pull request merged**
