### PR TITLE
WIP: uberon pattern work

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
@balhoff any idea what is happening here:

```bash
$ dosdp-tools query --obo-prefixes true --ontology ../../ontology/uberon-edit.obo --template skeleton_of_body_part.yaml --outfile ../data/skeleton_of_body_part.tsv
$ wc ../data/skeleton_of_body_part.tsv
      14      93    1728 ../data/skeleton_of_body_part.tsv
```

however, there should be a lot more than 14:

```
obo-grep.pl -r 'intersection_of: skeleton_of' ../../ontology/uberon-edit.obo | obo-grep.pl -r 'intersection_of: UBERON:0010912' - | obo-filter-tags.pl -t id -t name -t intersection_of - | grepcid
Tags: intersection_of, id, name
71
```

e.g. includes

```yaml
id: UBERON:5111982 ! manual digit 7 digitopodial skeleton
name: manual digit 7 digitopodial skeleton
intersection_of: UBERON:0010912 ! subdivision of skeleton
intersection_of: skeleton_of UBERON:5011982 ! manual digit 7 plus metapodial segment
```

but this one isn't in the csv

**Comment by cmungall** [comment]
another one:

```yaml
id: UBERON:0006356 ! epigastric vein
name: epigastric vein
intersection_of: UBERON:0001638 ! vein
intersection_of: drains UBERON:0006635 ! anterior abdominal wall
```

doesn't show up in 

```yaml
UBERON:0001638"
  
relations: 
  drains: "RO:0002179"


vars:
  structure: "'multicellular anatomical structure'"
equivalentTo:
  text: "('vein' and ('drains' some %s))"
  vars:
    - structure
```

**Review by dosumis — APPROVED** [review]
Patterns all look good to me.  @cmungall  - assume the aim is to move generation of these logical defs permanently out into spreadsheets?

CC @anitacaron  for veins/arteries we should think about how we might comparisons/diffs to representation in HubMap ASCT+B

**Comment by matentzn** [comment]
The title of the PR says WIP (better use draft mode then saying WIP), is this ready to merge?

**Pull request merged**
