### PR TITLE
Subarachnoid space should not be part of brain fixes #2006

### LINKED ISSUE #2006: Subarachnoid space should not be part of brain
**Uberon term**
 
subarachnoid space
http://purl.obolibrary.org/obo/UBERON_0000315

**Bug description**

image

The meninges and the various membranes and spaces that comprise it are the outer part of both the brain and spinal cord.  They therefore should be part_of the CNS, not the brain.

https://en.wikipedia.org/wiki/Meninges#Subarachnoid_space

For optimum partonomy, it might make more sense for the space(s) to be part of the meninges (AKA meningeal cluster) or meninx
image

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Review by dosumis — APPROVED** [review]

**Comment by shawntanzk** [comment]
ERROR Only equivalent classes that have been asserted are allowed. Inferred equivalencies are forbidden.
ERROR Equivalence: <http://purl.obolibrary.org/obo/UBERON_0000315> == <http://purl.obolibrary.org/obo/UBERON_0039174>

Will check this out

**Comment by shawntanzk** [comment]
subarachnoid space == subarachnoid space of central nervous system

subarachnoid space is part of some meningeal cluster
meningeal cluster is bounding layer and part of of CNS  
therefore subarachnoid space is part of CNS 
therefore subarachnoid space is = subarachnoid space of central nervous system

**Comment by matentzn** [comment]
Awesome Thank you @shawntanzk! Thanks for doing it. Is your biological knowledge good enough to determine what is the most likely thing that is wrong?

**Comment by shawntanzk** [comment]
Solutions: 
1) meningeal layer should not be part_of CNS (it lines the CNS, but is it part of?) 
2) is there a need for subarachnoid space that is CNS? I'm not 100% sure, but I thought it was all in the CNS? thought it was all withing brain and spine?

**Comment by shawntanzk** [comment]
Pia mater covers brain and spinal cord 
arachnoid mater between pia and dural mater
dural mater covers brain and spinal cord
subarachnoid space between arachnoid and pia mater 

All the above is defs from uberon, therefore there really isn't a need for CNS subarachnoid space

**Comment by shawntanzk** [comment]
I removed subarachnoid space of the CNS and place that and synonyms in subarachnoid space - should fix it

**Comment by cmungall** [comment]
I agree with @shawntanzk's analysis and fixes

**Pull request merged**
