### PR TITLE
add 'lateral wall of nasal cavity'

### LINKED ISSUE #3145: add 'lateral wall of nasal cavity'
**Preferred term label:**
lateral wall of nasal cavity

**Synonyms**
'nasal lateral wall'
'lateral wall of the nose'
NCIT:C160988

**Definition (free text, please give PubMed ID)**
An anatomical wall that is part of the nasal cavity. The lateral walls of the nasal cavity are spiral shaped mucosal folds that overlie the turbinate and sinus ducts draining into the ostia. The spiral shape of the turbinate increases the surface area for the inspired air.
PMID:31334952

**Parent term**
anatomical wall UBERON:0000060
'part of' nasal cavity UBERON:0001707

This term is used in: https://hcmi-searchable-catalog.nci.nih.gov/model/HCM-CSHL-0634-C30 to describe the tissue origin of this organoid

### PR DESCRIPTION
**Pull request by paulacalipho**
fixes #3145

### CODE REVIEW

**Comment by anitacaron** [comment]
#gogoeditdiff

**Comment by paulacalipho** [comment]
Thanks @aleixpuigb I added part of because I saw other wall described as part of. Example: wall of anal canal

**Comment by paulacalipho** [comment]
@aleixpuigb Should I try 'surrounds' some ?

**Comment by aleixpuigb** [comment]
> @aleixpuigb Should I try 'surrounds' some ?

Yes, that should solve the problem.

**Comment by paulacalipho** [comment]
@aleixpuigb yes, true, I saw it! thanks

**Comment by anitacaron** [comment]
> > Thanks @aleixpuigb I added part of because I saw other wall described as part of. Example: wall of anal canal
> 
> Yes, in theory it would be the same pattern, and I would also have done the same. However, the canal is a conduit (involving the walls), while the nasal cavity is a space (without involving the walls). A good way to see if something is not right is to run the reasoner and check that you don't get `owl:Nothing`: image

Complementing Aleix's comment, you can check the explanation by clicking on the question mark, on the right side

Screenshot 2024-01-05 at 12 00 22


Screenshot 2024-01-05 at 11 56 48

**Comment by paulacalipho** [comment]
@anitacaron perfect, many thanks! (Disjoint classes)

**Comment by anitacaron** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
