### PR TITLE
Cross Term Label-Synonym Violation QC

### PR DESCRIPTION
**Pull request by vasvir**
This PR detects synonym-synonym and label-synonym across different Terms (UBERON Ids).

Another implementation (but with the same logic and functionality) of this check was
used to detect and fix (merged) the followings issues:

* https://github.com/obophenotype/uberon/pull/2465
* https://github.com/obophenotype/uberon/pull/2470
* https://github.com/obophenotype/uberon/pull/2506

The backstory is in https://github.com/obophenotype/uberon/issues/2424

The existing
https://robot.obolibrary.org/report_queries/duplicate_exact_synonym detects
only synonym-synonym violations. It was in reported in
https://github.com/ontodev/robot/issues/607 but closed at the time.

The existing
https://robot.obolibrary.org/report_queries/duplicate_label_synonym check
for all label-synonym duplication both in the same Term and across
different terms. The duplicity in the same term is a warning but the
duplicity across different terms should be an error.

In this PR the test is case insensitive because a downstream applications
have a strong possibility to be case insensitive in order to maximize
coverage.

Currently this test flags 3 errors and as such cannot be merged. I will try
to address the issues revealed by this test and are shown below in future PR hoping
that at some point this PR will be merged.

entity,property,value
http://purl.obolibrary.org/obo/UBERON_0002633,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,nV
http://purl.obolibrary.org/obo/UBERON_2005093,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,NV
http://purl.obolibrary.org/obo/UBERON_2000438,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,phy
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,PHY
http://purl.obolibrary.org/obo/UBERON_0013560,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,Prelimbic area
http://purl.obolibrary.org/obo/UBERON_8440032,http://www.w3.org/2000/01/rdf-schema#label,prelimbic area

Thanks @matentzn and @anitacaron for the guidance and the hand-holding.

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Excellent! Thank you very much @vasvir, from a distance, this looks good to me!

**Comment by vasvir** [comment]
@matentzn some help on this please.

I am trying to follow @shawntanzk suggestion and add an exclusion clause for when the synonym is EXACT ABBREVATION

However I don't know how to select (or exclude) the ABBREVATION annotation in SPARQL.

I did the equivalent of SELECT * in order to get an initial dump and work my way from there

```
SELECT ?entity ?property ?value WHERE {
  ?entity ?property ?value
  FILTER (!isBlank(?entity))
  FILTER NOT EXISTS { ?entity owl:deprecated true }
} ORDER BY ?entity
```
but I don't see anywhere  the ABBREVATION or something similar.

If I grep 8440028 in the output of the above query. I don't anywhere that PHY is an Abbreviation. Only that is excact.

```
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasDbXref,MBA:154
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,PHY
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,nuclei perihypoglossales
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,perihypoglossal complex
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,perihypoglossal nuclear complex
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym,satellite nuclei
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#hasOBONamespace,uberon
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.geneontology.org/formats/oboInOwl#id,UBERON:8440028
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://www.w3.org/2002/07/owl#Class
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.w3.org/2000/01/rdf-schema#label,Perihypoglossal nuclei
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.w3.org/2000/01/rdf-schema#subClassOf,_:b21169
http://purl.obolibrary.org/obo/UBERON_8440028,http://www.w3.org/2000/01/rdf-schema#subClassOf,http://purl.obolibrary.org/obo/UBERON_0002308




```

**Comment by shawntanzk** [comment]
@anitacaron - wonder if you can help with this, this is way beyond my super limited sparql skills >.< thanks :D

**Comment by anitacaron** [comment]
Hi @vasvir, the ABBREVIATION is an annotation for the type of synonym. It would help if you looked into the axioms to find it.

Use this SPARQL snippet code to search for them:
```sparql
PREFIX oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?subject ?synonym WHERE {
  ?subject oboinowl:hasExactSynonym ?synonym .
  ?_x a owl:Axiom;
       owl:annotatedSource ?subject;
       owl:annotatedProperty oboinowl:hasExactSynonym;
       owl:annotatedTarget ?synonym;
       oboinowl:hasSynonymType <http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION> .
}
```

In UBERON:8440028, it doesn't have the synonym type for PHY, so you won't find it in this case. We need to include this annotation and verify if others are in the same issue.

You can see all the positive cases with the SPARQL query I shared.

**Comment by vasvir** [comment]
Thanks a lot.

This seems to work. Now I have to make it work for my check.

BTW,

UBERON:8440028 PHY is an abbreviation and It was in #2643 that merged yesterday so you probably have a older checkout.

Your query shows it though so we are good.

Thanks again

**Comment by anitacaron** [comment]
Ah, yes, you're right. I run the query in the uberon release. Good, you already fixed it. Thank you, @vasvir.

**Comment by vasvir** [comment]
I fixed the query and now it does not flag ABBREVIATION synonyms as errors but I managed to botch the git history.

So If you don't want to merge I understand it.

I will try to fix it when my git foo is stronger...

**Comment by vasvir** [comment]
I accidentally closed my PR and cannot get it back. Sorry evreybody. New PR is #2681

**Pull request closed without merging**
