### PR TITLE
revise def and logical axiom to cranial temporal crest

### LINKED ISSUE #2882: temporal crest
**Uberon term**
temporal crest

**Suggested revision of textual definition**

temporal crest
def.: A ridge or similar projection connected to the temporal lines and nuchal crest on the squamous part of the occipital bone. It bounds the posteroventral part of the temporal fossa.

ref.: https://www.researchgate.net/publication/325258124_Morphological_Study_on_the_Skull_of_Wild_Boar_of_Mizoram_Sus_scrofa

EQ: crest and part of some temporal bone and part of some occipital bone

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #2882

### CODE REVIEW

**Comment by megbalk** [comment]
@nicolevasilevsky I am confused, did the changes from 2881 get moved here?

**Comment by nicolevasilevsky** [comment]
Hi @megbalk is this the 2881 that you are referring to?
https://github.com/obophenotype/uberon/pull/2881

Looks like these are different changes than what is on this PR

**Comment by nicolevasilevsky** [comment]
This PR added the EQ though - do you want to add the EQ on the other PR?

Also, I'm not sure why this failed.

**Review by megbalk — APPROVED** [review]

**Comment by anitacaron** [comment]
I fixed the conflict.

**Comment by anitacaron** [comment]
Because this PR was already approved, I'll serialize the edit file here again to avoid future conflicts.

**Pull request merged**
