### PR TITLE
Uberon Editor SOP

### PR DESCRIPTION
**Pull request by shawntanzk**
@dosumis - we need to discuss which of the relations to have in relations guide, the list is pretty long: https://docs.google.com/spreadsheets/d/1ScwOdD0KAphfmpBLZ9MMJa0jfkmH_uu-UoVEK7Vx2GQ/edit?usp=sharing

### CODE REVIEW

**Comment by dosumis** [comment]
110 if we remove duplicates due to multiple defs.  

I think it would be really useful to generate a report as a starting point with relations grouped by position in OP hierarchy*, usage numbers and one example for each. We could generate from UberGraph.   This would give us a nice summary of how Uberon is structured, showing where relations are used comprehensively vs spottily, as well as pointing to how to prioritise.

@anitacaron could take this on.

* possible challenge comes from multiple inheritance in property graph, but I think that shouldn't be too hard to clean up by hand.

**Comment by anitacaron** [comment]
I can create two reports, one with the usage and an example and the other with the OP hierarchy. Then need to merge both manually.

**Comment by shawntanzk** [comment]
@bvarner-ebi & @dosumis I've done a couple of relations for the guide, would like you to have a look first before I continue on in this format. 
In regards to using the top few OP in the heirachy, they seem to point to similar uses, which can probably be squashed down or something? (Not sure about searching and all though). Maybe something to discuss in next docs meeting?

property | p_label | sub_property | s_label
-- | -- | -- | --
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0000122 | in posterior side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0000123 | in anterior side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0000124 | in proximal side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0000125 | in distal side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0000126 | in lateral side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0001100 | in superficial part of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0001101 | in deep part of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0001113 | preaxialmost part of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0001115 | postaxialmost part of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0005001 | intersects midsagittal plane of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0015101 | in dorsal side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0015102 | in ventral side of
http://purl.obolibrary.org/obo/BFO_0000050 | part of | http://purl.obolibrary.org/obo/BSPO_0020001 | in central side of

**Comment by dosumis** [comment]
Basic structure and content looks good.  (The 'at all times; clause can be hard to commit to when representing development, but we can gloss that).  I think it will be sufficient just to have @bvarner-ebi subedit for minor corrections.

The example of grouping relations using the hierarchy is exactly what I was looking for.

**Comment by shawntanzk** [comment]
Thanks @dosumis - will continue working in this way then
@bvarner-ebi let me work on some more relations first, ill ping you once I'm ready for you to subedit

**Comment by shawntanzk** [comment]
@dosumis - am I right to say that the audience is someone who has ontology experience but needs to know the nuances of uberon? 
@bvarner-ebi happy for you to change and edit anything directly, don't need to make suggestions etc.
Other than that I think this is ready for a first pass

Thanks

**Comment by shawntanzk** [comment]
@bvarner-ebi could you help see this through as part of docs work please. Thanks.

**Review by dosumis — APPROVED** [review]
Good enough to merge.  We can iteratively improve.

**Pull request merged**
