### PR TITLE
Polysemy: NV. Demote synonymity to RELATED in UBERON:2005093

### PR DESCRIPTION
**Pull request by vasvir**
This PR tries to resolve the 4 of 4 of issues mentioned in #2424

The issue also blocks QC PR #2640

The problem that is addressed here is that

* nV is listed as an EXACT synonym of UBERON:0002633 motor nucleus of trigeminal nerve
* NV is listed as an EXACT synonym of UBERON:2005093 nasal vein

The proposed solution demotes NV to RELATED for nasal vein.  From a cursory
web search in google and pubmed looks like that "nv" is more often
associated with "motor nucleus of trigeminal nerve" than the "nasal vein".

In my opinion both synonyms should be deleted since they are not used widely
enough and they represent a significant risk of misinterpretation by any
automated system. Having said the path of minimum change was selected for this PR.

Tagged @matentzn as requested.

### CODE REVIEW

**Comment by matentzn** [comment]
Ideally, there would be a way to capture acronyms as a special synonym type to avoid ambiguity like this.. For now I am ok with this change, as it is tiny, but allows a nice QC check to be switched on. Technically, I would perceive this case here as an exception to the check though!

**Comment by shawntanzk** [comment]
see https://github.com/obophenotype/uberon/pull/2640#issuecomment-1252539710

**Review by shawntanzk — APPROVED** [review]
looks good - probably would still let qc run through, but can't see why it would fail with a change like that. Thanks heaps :)

**Comment by vasvir** [comment]
Well all my PR are failing at post_comment...

**Comment by shawntanzk** [comment]
> Well all my PR are failing at post_comment...

Yeah sorry about that, it requires github secret token something something and cause you arent a member, it has issues I think. I'll merge it in :) thanks

**Comment by vasvir** [comment]
It is somewhat disheartening for new folks... But then again I can understand these things may resist in various spectacular ways when you try to fix them and at the end sometimes it is really difficult.

**Comment by shawntanzk** [comment]
> It is somewhat disheartening for new folks... 

Yeah I totally understand, and I'm sorry about it, but we really honestly appreciate your help with this :) 
The diff thing is annoying, cause it's actually really pushing github actions, but it actually does help (at least me) in the review process. The action failing at comment part when it's not one of us creating the PR - I still can't quite figure out how to get around it, but if you have any suggestions, super welcome :) 
PS if you have any suggestions for anything at all, please do let us know, we are 100% committed to democratising editing the ontology and all, but legit, thanks so much for your contributions!

**Pull request merged**
