### PR TITLE
2023-04-19 Release

### PR DESCRIPTION
**Pull request by anitacaron**
[The diff in Markdown](https://github.com/obophenotype/uberon/blob/2d64eeda6ba2a8131e1c8662c6e260bc3127fc7a/src/ontology/diffs/uberon-diff.md).

### CODE REVIEW

**Comment by aleixpuigb** [comment]
Hi @anitacaron:
Not sure about this change:
image
In the most updated version we don't see it reflected:
image
How is this report interpreted?

**Review by bvarner-ebi — APPROVED** [review]
After a cursory review with some spot checks with @aleixpuigb, I did not find obvious breaking changes.

As noted [here](https://github.com/obophenotype/uberon/pull/2868#issuecomment-1514811508), we were unable to tie some lines from the markdown diff report to what is present in the uberon-edit.owl file. If this is not expected, please advise how best to proceed.

**Comment by bvarner-ebi** [comment]
> It's probably inferred axioms.

'acellular membrane' is inferred (ELK 0.5.0), but 'acellular anatomical structure' is manually asserted, so unsure how to make sense of 'acellular anatomical structure' being marked as "Removed" in the report.

**Comment by anitacaron** [comment]
There's also a [robot reduce](http://robot.obolibrary.org/reduce) command to remove all redundant subClassOf axioms.

**Pull request merged**
