### PR TITLE
change snout synonym

### PR DESCRIPTION
**Pull request by megbalk**
change synonym type for muzzle from "related" to "exact" for snout
issue #2581

### CODE REVIEW

**Comment by shawntanzk** [comment]
@megbalk - just a heads up, @paolaroncaglia has left the team, so you might want to seek out another reviewer.

**Comment by shawntanzk** [comment]
I'm confused - why is there two different PR with basically the same thing? This and https://github.com/obophenotype/uberon/pull/2583

**Comment by megbalk** [comment]
I don't know...

**Comment by nicolevasilevsky** [comment]
I think that is my fault, looks like we both did a PR for the same ticket. I'll close my duplicate PR.

**Review by shawntanzk — APPROVED** [review]
Just to double check - all snouts are called muzzles too yeah? like its not species specific? I see that the xref is for mouse anatomy, and quick googling seems to suggest exact so I will approve this PR, but just wanted to make sure that the above is true before you merge.

**Comment by megbalk** [comment]
@shawntanzk so it seems muzzle is a mammal term, so snout is an exact synonym of muzzle but muzzle isn't of snout?

**Comment by shawntanzk** [comment]
In that case I think narrow synonym might be the accurate one to use, though I can understand the uses of related as it seems that it is used synonymously thought not entirely accurately? - see https://oboacademy.github.io/obook/reference/synonyms-obo/ (I assume snout is general, and muzzles are snouts of mammals?) 
CL is **_technically_** species non-specific, but you probably will find that it kinda is still biased towards mammals, esp humans, and because of that I'm kinda not fully against exact if there is a use case, but preference would be to leave it as related at this point

**Comment by megbalk** [comment]
I agree. I made the changes. May I merge?

**Comment by shawntanzk** [comment]
for me, looks good, up to your discretion to merge :) thanks!

**Pull request merged**
