### PR TITLE
DO NOT MERGE. Re-save OBO with Protege 5.5.0.

### PR DESCRIPTION
**Pull request by balhoff**
Just a proactive re-save to clean up future PRs.

### CODE REVIEW

**Comment by balhoff** [comment]
This is failing because the perl check doesn't like annotations that are stored as relationships in OBO:

```
./util/check-obo-for-standard-release.pl --xref-abbs GO.xrf_abbs --disable-multiply-labeled-edge --disable-valid-id-space --disable-isa-incomplete --disable-ascii-check --disable-has-definition --disable-bad-pmid --disable-ontology-declaration-check --disable-referenced-id-syntax-check --disable-owl-axiom-check --disable-is-symmetric-check uberon_edit.obo > uberon_edit.obo-gocheck.tmp && mv uberon_edit.obo-gocheck.tmp uberon_edit.obo-gocheck
221 :: ERROR: logic-axiom-references-obsolete: UBERON:0023942 has relationship to NCBITaxon:9989
222  :: ERROR: logic-axiom-references-obsolete: UBERON:0023938 has relationship to NCBITaxon:9989
223  :: ERROR: logic-axiom-references-obsolete: UBERON:0000960 has relationship to http://upload.wikimedia.org/wikipedia/commons/d/d7/Gray780.png
224  :: ERROR: logic-axiom-references-obsolete: UBERON:0005889 has relationship to XAO:0000216
225  :: ERROR: logic-axiom-references-obsolete: UBERON:0006693 has relationship to GO:0007592
226  :: ERROR: logic-axiom-references-obsolete: UBERON:0023939 has relationship to NCBITaxon:9989
227  :: ERROR: logic-axiom-references-obsolete: UBERON:0000470 has relationship to https://github.com/obophenotype/uberon/issues/489
228  :: ERROR: logic-axiom-references-obsolete: UBERON:0002431 has relationship to https://github.com/obophenotype/uberon/issues/436
```

**Comment by matentzn** [comment]
What should be done about this?

**Comment by matentzn** [comment]
I think the problem was something else.. Give me a min.

**Comment by cmungall** [comment]
we can just add `--disable-logic-axiom-references-obsolete` but of course we want to move away from obo level checks, once we are confident we have equivalent functionality in robot

we may want to redo this PR as there have been changes...

**Pull request closed without merging**
