### PR TITLE
3056 Fix duplicate mappings

### PR DESCRIPTION
**Pull request by gouttegd**
This is a first pass at fixing the duplicated cross-references highlighted in #3056.

### CODE REVIEW

**Comment by gouttegd** [comment]
Not sure what the heck is going on with the CI action on this PR… The workflow was seemingly triggered twice, one run terminated without problem, the other has been stuck with a “starting job” message for more than 90 minutes and there’s no way to cancel it…

**Comment by anitacaron** [comment]
I clicked on re-run workflow, and the one stuck disappeared.

**Comment by anitacaron** [comment]
I can't edit the filter in the [complete list](https://docs.google.com/spreadsheets/d/1tvi2UR5Sp6yjlLlRj6JkQfDO6Gd6AqwitBRd8FCxiL0/edit#gid=0) to check if everything conforms to it in this PR.

**Comment by gouttegd** [comment]
@anitacaron Sorry, I didn’t know that one needed write access on a Google Calc spreadsheet merely to change the filters. I’ve cleared all the filters.

**Review by rays22 — APPROVED** [review]
The changes look reasonable to me.

**Pull request merged**
