### PR TITLE
Addresses #2960 adds has_part CT-AS

### LINKED ISSUE #2960: Add 'has part' cell types in respiratory structures
Related to #2904, some cell types are found in multiple tissues. To avoid the creation of numerous subclasses of a cell type only differing on their location, we can use the object property 'has part'. Some of the CL classes need to be imported.

Structures that need this axiom will be presented in this format:
Anatomical structure (AS) --> Cell type (CT)
Where AS will include SubclassOF ’has part’ some CT.

- [x] epithelium of segmental bronchus --> club cell
- [x] epithelium of bronchiole --> club cell
- [x] pulmonary alveolar parenchyma --> type I pneumocyte
- [x] pulmonary alveolar parenchyma --> type II pneumocyte
- [x] epithelium of segmental bronchus --> brush cell of bronchus
- [x] epithelium of segmental bronchus --> basal epithelial cell of tracheobronchial tree
- [x] epithelium of lobar bronchus --> basal epithelial cell of tracheobronchial tree
- [x] epithelium of lobar bronchus --> ciliated cell of the bronchus
- [x] epithelium of segmental bronchus --> ciliated cell of the bronchus
- [x] bronchus smooth muscle --> bronchial smooth muscle cell
- [x] pulmonary alveolar parenchyma --> lung pericyte
- [x] pulmonary nerve plexus --> sympathetic neuron
- [x] epithelium of segmental bronchus --> pulmonary ionocyte
- [x] epithelium of lobar bronchus --> pulmonary ionocyte
- [x] cartilage of bronchus --> tracheobronchial chondrocyte
- [x] lobar bronchus mesenchyme --> tracheobronchial smooth muscle cell
- [x] epithelium of segmental bronchus --> lung goblet cell
- [x] epithelium of segmental bronchus --> lung neuroendocrine cell
- [x] epithelium of bronchiole --> lung ciliated cell
- [x] terminal bronchiole epithelium --> lung ciliated cell
- [x] smooth muscle tissue of terminal bronchiole --> bronchiolar smooth muscle cell
- [x] smooth muscle tissue of respiratory bronchiole --> bronchiolar smooth muscle cell

### PR DESCRIPTION
**Pull request by aleixpuigb**
Fixes #2960 adds has_part CT-AS and imports from CL

### CODE REVIEW

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by anitacaron** [comment]
Adding your ORCID as a contributor when editing terms would be a good practice from now on. 😃

**Comment by aleixpuigb** [comment]
@anitacaron there are many changes that I suppose they come from refreshing imports.

**Comment by anitacaron** [comment]
You're right. The names for ORCID come from the new RO release.

**Comment by anitacaron** [comment]
It would be good to import [orcidio](https://github.com/cthoyt/orcidio)](https://github.com/cthoyt/orcidio) here too.

**Comment by cmungall** [comment]
These look good. I don't believe they fall into the antipatterns here #2963 -- but we should still document the patterns

**Review by cmungall — APPROVED** [review]

**Comment by aleixpuigb** [comment]
Thank you @cmungall and thank you for creating the associated ticket https://github.com/obophenotype/uberon/issues/2963 to create a DP document.

**Pull request merged**
