### PR TITLE
Merge phenoscape-ext into uberon_edit.obo.

### PR DESCRIPTION
**Pull request by balhoff**
This is not going to be easy to review; the diff is too big to view here.

### CODE REVIEW

**Comment by balhoff** [comment]
There is a little bit of stuff in the owl-axioms header, and I can't figure out why it's being put there.

**Comment by balhoff** [comment]
I changed to draft. I need to inspect the diff more.

**Comment by cmungall** [comment]
sorry @matentzn and I have a long running branch where we renamed and moved the edit file...

**Comment by balhoff** [comment]
Want me to open a PR to that branch? Have you been merging other recent commits into there?

**Comment by balhoff** [comment]
There are numerous problems with identical definitions across terms, and missing definition dbxrefs.

**Comment by balhoff** [comment]
@wdahdul and I will add commits here until the QC passes.

**Comment by matentzn** [comment]
Just make sure you dont touch other files - as long as it is just one or two, its easy to migrate..

**Pull request merged**
