### PR TITLE
Add classes UBERON:8410008 left colic artery and UBERON:8410009 right…

### PR DESCRIPTION
**Pull request by paolaroncaglia**
… colic artery

Addresses #1702 and #1703

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@dosumis (for after the holidays!)
Not entirely sure about the diff. If it's any help, I duplicated the first term in Protege to obtain the second term (to keep the ORCID etc) and then edited the second term. Thanks.

**Review by dosumis — CHANGES_REQUESTED** [review]
Def xrefs in regular xrefs.  Please move.  (check fail caused by missing definition ref)

**Review by dosumis — COMMENTED** [review]
Also wondering how this got in: AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#id> <http://purl.obolibrary.org/obo/UBERON_8410009> \"UBERON:8410008\"^^xsd:string)\n)

Probably doesn't do any harm, but could delete (will appear as annotation `id: UBERON:8410008` in Protege

**Comment by paolaroncaglia** [comment]
AI for me: delete the id annotation UBERON:8410008

**Comment by paolaroncaglia** [comment]
@dosumis 
I edited the dbxrefs in both classes, and removed the extra id in UBERON_8410009.

**Review by dosumis — APPROVED** [review]

**Pull request closed without merging**
