### PR TITLE
assert UBERON:7500102 parent as Uberon Anatomical Entity 

### PR DESCRIPTION
**Pull request by shawntanzk**
Related to https://github.com/obophenotype/uberon/issues/2934 (and partly fixes it) 
@anitacaron hope you dont mind putting you as a reviewer, wanted your thoughts on if this is ok way to fix for now
@bvarner-ebi &/or @aleixpuigb - not sure if you have any suggestions on better parent than just anatomical entity
(note that currently during materialisation step in release, it gets placed under Anatomical Entity, but CARO version (relates to https://github.com/obophenotype/uberon/issues/2296)

### CODE REVIEW

**Comment by shawntanzk** [comment]
Replaced: 0
Killed
make: *** [uberon.Makefile:1136: reports/basic-allcycles] Error 137

😭

will look into this - converting to draft for now

**Comment by shawntanzk** [comment]
oh wait, killed is probably memory issue, will try to rerun the QC

**Comment by shawntanzk** [comment]
It was just memory issues heh
while im commenting, #gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]
Out of the scope of this PR, but given the definition, I miss some child terms that are part of the preorbital bone region (jugal bone, lacrimal bone and maxilla bone).

**Comment by shawntanzk** [comment]
> Out of the scope of this PR, but given the definition, I miss some child terms that are part of the preorbital bone region (jugal bone, lacrimal bone and maxilla bone).

I'll open a ticket on this and we can solve it there :) thanks heaps

**Comment by shawntanzk** [comment]
merging to make next release - if there is a better parent term that can be used, please open a new PR for it. Thanks :)

**Pull request merged**
