### PR TITLE
Paolaroncaglia issue 1657

### PR DESCRIPTION
**Pull request by paolaroncaglia**

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@dosumis 
Could you review please? Trying to resolve trivial merge issue from https://github.com/obophenotype/uberon/pull/1707 - the first one in my Uberon PRs. Thanks.

**Review by dosumis — APPROVED** [review]

**Comment by dosumis** [comment]
@matentzn - Looks like we've hit limits monthly limit for travis.com on obophenotype a few days after I moved the repos over from travis.org. Move to GitHub actions + moving some repos off the org needed ASAP.

**Comment by matentzn** [comment]
This is not travis - this is docker.. the rate limit refreshes every 6 hours. Moving to GH actions won't fix this, unfortunately..

**Comment by dosumis** [comment]
>  is not travis - this is docker..

Ahh - that's a relief.  I guess we can put up with this.

**Pull request merged**
