### PR TITLE
Add glomus coccygeum

### PR DESCRIPTION
**Pull request by paolaroncaglia**
Addresses #1674

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@matentzn @shawntanzk could one of you help me interpret the fail message details, please? Much appreciated!

**Comment by shawntanzk** [comment]
`iconv: illegal input sequence at position 12175012`

guessing that there is a symbol or something that is illegal
 will try to find it, really should document how to search for the position

**Comment by shawntanzk** [comment]
@paolaroncaglia there ' in `Luschka's gland` was a wrong ' if that makes sense lol, fixed it

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> `iconv: illegal input sequence at position 12175012`
> 
> guessing that there is a symbol or something that is illegal will try to find it, really should document how to search for the position

Exactly! I did see that but had no idea where to look. Thank you.

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> there ' in `Luschka's gland` was a wrong ' if that makes sense lol, fixed it

Thanks for finding and fixing!

**Pull request merged**
