### PR TITLE
Fovt calcaneus2

### PR DESCRIPTION
**Pull request by megbalk**
#2022

### CODE REVIEW

**Review by balhoff — APPROVED** [review]

**Review by cmungall — APPROVED** [review]
This is great, thanks!

It would be good to come up with some DPs here, but spatial DPs are non-trivial, it's easy to think you are saying something in OWL and actually be saying something else

why doesn't have 7500092 have "articular" in the name?

would it not be good to have a grouping class for AFfToC?

these aren't blockers though

**Comment by megbalk** [comment]
@cmungall are you suggesting the name be "anterior articular facet..."?

**Comment by megbalk** [comment]
added articular to the terms.

**Comment by cmungall** [comment]
Replaced by #2052

**Pull request closed without merging**
