### PR TITLE
Add ethmoidal veins

### PR DESCRIPTION
**Pull request by rays22**
requested by HUBMap (HRA-VCCF).

### CODE REVIEW

**Review by aleixpuigb — APPROVED** [review]
I approve although I had two doubts:
- 'ethmoidal vein' part_of 'ethmoidal region': I am not complete sure that the entirety of the vein is in the ethmoidal region, although the images are not 100% clear and it could be.
image
- I have found a couple of sources that stated that the posterior ethmoidal vein tributes to a different vein than the superior ophtalmic vein (https://doi.org/10.1167/iovs.02-0865, https://doi.org/10.1007/978-3-031-40697-3_23), perhaps the cavernous sinus. However it was not clear and other sources support that it tributes intp the SOV.

**Comment by rays22** [comment]
Thanks @aleixpuigb for your comments.

> I approve although I had two doubts:
> 
> * 'ethmoidal vein' part_of 'ethmoidal region': I am not completely sure that the entirety of the vein is in the ethmoidal region, although the images are not 100% clear and it could be.

OK, I have changed 'ethmoid region' to the broader term ['face'](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001456), where 'face' is meant to be a subdivision of the head, and it includes deeper structures under the visible surface.

> * I have found a couple of sources that stated that the posterior ethmoidal vein tributes to a different vein than the superior ophtalmic vein (https://doi.org/10.1167/iovs.02-0865, https://doi.org/10.1007/978-3-031-40697-3_23), perhaps the cavernous sinus. However it was not clear and other sources support that it tributes into the SOV.

OK, I have updated the superior ophthalmic vein tributary.

**Review by aleixpuigb — DISMISSED** [review]
I approve this PR.
We have discussed on slack if 'ethmoidal vein' should be part of the face, similar to 'sublingual vein'. It has been discussed before about what structures are part of the face https://github.com/obophenotype/uberon/issues/3310 and Uberon ontology calls.

**Comment by rays22** [comment]
> I approve this PR. We have discussed on slack if 'ethmoidal vein' should be part of the face, similar to 'sublingual vein'. It has been discussed before about what structures are part of the face #3310 and Uberon ontology calls.

Just to be on the safe side, I have changed the `location` slot for 'ethmoidal vein' to [UBERON:0002200 vasculature of head](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002200).

**Review by aleixpuigb — APPROVED** [review]
All looks good, thanks!

**Pull request merged**
