### PR TITLE
Refactoring edit file and pipeline to allow community editing

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
@matentzn @dosumis @balhoff @wdahdul @mellybelly @nicolevasilevsky   anyone should be able to checkout/make branch/edit in protege/commit/PR in uberon now!

More docs required but it;'s a start!

**Comment by nicolevasilevsky** [comment]
awesome!

**Comment by balhoff** [comment]
Cool! Have you merged in phenoscape-ext?

**Comment by wdahdul** [comment]
@cmungall Just to be sure, do we stop editing phenoscape-ext now?

**Comment by cmungall** [comment]
I have not merged it in yet but that should be easy

**Pull request merged**
