### PR TITLE
adding life-stages-minimal subset

### PR DESCRIPTION
**Pull request by cmungall**
For #2422

### CODE REVIEW

**Comment by shawntanzk** [comment]
@matentzn think it should be a straightforward merge, but didn't want to do it without you given that you commented on the ticket. Thanks

**Comment by matentzn** [comment]
@shawntanzk can you:

- [ ] Run `sh run.sh make update_repo` on this branch, commit changes
- [ ] Make sure there is a goal like this in uberon.Makefile:

```
subsets/life-stages-minimal.owl: subsets/merged-partonomy.owl
	$(eval TERM_ID := $(TERM_appendicular))
	$(SUBSETCMD)
```

I do not know what `TERM_appendicular` should be? Maybe of you scroll a bit up and down in the Makefile you can guess it.. A new variable like `$(TERM_lifestages)` probably, not sure what the id is but maybe there is a "life stage" class in Uberon?

**Comment by shawntanzk** [comment]
diff.yml now gets added when I update repo, I assume you updated the ODK build for this? I have removed it from here as it won't work as is for UBERON just wanted to check. Do note that this also  downgrades from 1.3.1 to 1.3.0 - the changes seem negative :( Happy to revert till 1.3.1 fully out?

**Comment by matentzn** [comment]
I updated it from my machine, can you pull?

Let's hope it just works..

**Comment by matentzn** [comment]
I shared it in uberon channel again to have chris take a look. It seems ok to me.

**Review by matentzn — APPROVED** [review]

**Pull request merged**
