### PR TITLE
Assert the exocrine pancreas to be part of the digestive system

### LINKED ISSUE #3208: "pancreas" (UBERON:0001264) not part of "digestive system" (UBERON:0001007) or "endocrine system" (UBERON:0000949)?
**Uberon term**
"pancreas" (UBERON:0001264)

**Suggested revision and reasons**
should be part of
  "digestive system" (UBERON:0001007) 
and
  "endocrine system" (UBERON:0000949)

It seems to be classified in the expected manner in
  Danio dangila (NCBITaxon:7954)
  Xenopus (NCBITaxon:8353)

### PR DESCRIPTION
**Pull request by rays22**
* UBERON:0001007 'exocrine pancreas'

Fix #3208

### CODE REVIEW

**Comment by anitacaron** [comment]
Hi Ray, which Protege version are you using? There are many diffs not related to this PR 😄

**Comment by rays22** [comment]
> Hi Ray, which Protege version are you using? There are many diffs not related to this PR 😄

I have used Protege 5.6.1 for this.

**Comment by rays22** [comment]
> Hi Ray, which Protege version are you using? There are many diffs not related to this PR 😄

@anitacaron ,
OK, I have re-edited `uberon-edit.obo` with Protege version 5.6.3. This time there is only one line of diff remaining that is unrelated to the intended assertion.

**Review by gouttegd — APPROVED** [review]
Looks good.

When merging, could you do a _squash_ merge please? So that the intermediate commits with the unwanted serialisation changes don’t end up in the history.

**Pull request merged**
