### PR TITLE
Add UBERON:8410022 and UBERON:8410023 (left and right colic arteries)

### PR DESCRIPTION
**Pull request by paolaroncaglia**
Addresses #1702 and #1703

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@dosumis 
For your review please.

**Review by dosumis — COMMENTED** [review]
@paolaroncaglia - Just want to check that you are sure about the use of EquivalentClass/Intersection definitions rather than subClassOf/relationship, in particular for the right colic artery.  Are you sure that no other arteries supply the ascending colon?  If in any doubt, please relax everything to subClassOf.  I'm not sure I see the use case for the full logical definitions in this case - do some people have multiple right colic arteries?

**Comment by paolaroncaglia** [comment]
@dosumis 

> Just want to check that you are sure about the use of EquivalentClass/Intersection definitions rather than subClassOf/relationship, in particular for the right colic artery. Are you sure that no other arteries supply the ascending colon? If in any doubt, please relax everything to subClassOf. I'm not sure I see the use case for the full logical definitions in this case - do some people have multiple right colic arteries?

You're absolutely right, I was being overzealous in my new findings of Uberon properties. Fixed now, thanks.

**Comment by paolaroncaglia** [comment]
@dosumis 
conflict resolved

**Review by dosumis — APPROVED** [review]

**Pull request merged**
