### PR TITLE
Adding instar larva stage terms

### LINKED ISSUE #1540: NTRs: specific instar larva stages
Name | Value
-- | --
Label | first instar larva stage
Definition | The first stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage

Name | Value
-- | --
Label | second instar larva stage
Definition | The second stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage

Name | Value
-- | --
Label | third instar larva stage
Definition | The third stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage
Alternative term | third instar larva
Definition source | IDOMAL:0000658 third instar larva

Name | Value
-- | --
Label | fourth instar larva stage
Definition | The fourth stage of instar larva stage.
Parent | UBERON_0004730 instar larval stage
Alternative term | fourth instar larva
Definition source | IDOMAL:0000659 fourth instar larva

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1540

### CODE REVIEW

**Review by cmungall — DISMISSED** [review]
conflict

**Comment by nicolevasilevsky** [comment]
I think this conflict has been addressed.

Come someone review/merge this?

@cmungall @dosumis ?

**Comment by cmungall** [comment]
@nicolevasilevsky I don't think IDOMAL is an appropriate def xref here. Is there a primary source? By all means xref the concept if they are the same.

@dosumis - is this appropriate for uberon? Is Nth instar meaningful in a cross-insecta sense?

**Review by dosumis — APPROVED** [review]

**Comment by dosumis** [comment]
@Clare72 we should make sure FBdv gets Xrefs for these terms

**Comment by matentzn** [comment]
@dosumis please assign someone to merge

**Review by dosumis — APPROVED** [review]
Don't see anything wrong with these - apart from that some insects have more than 4 (Monarch butterflies have 5).

**Pull request merged**
