### PR TITLE
First attempt adding taxon constraint QC back

### LINKED ISSUE #2374: Include proper taxon constrait checking in general CI
For debugging purposes, I am running:

```
sh run.sh make reports/taxon-constraint-check.txt MIR=false IMP=false PAT=false BRI=true -B
robot explain -i tmp/uberon-edit-plus-tax-equivs.owl --reasoner ELK -M unsatisfiability --unsatisfiable random:10 --explanation unsat.md
```

Then pasting unsat.md in GitHub

_Originally posted by @matentzn in https://github.com/obophenotype/uberon/issues/2367#issuecomment-1084855364_

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #2374

### CODE REVIEW

**Comment by matentzn** [comment]
@shawntanzk if you have time, can you check out this PR and add an xref that would (or should) definitely break the taxon constraints rules? Seems like the ZFA one that previously broke stuff doesn't today. Wanna make sure that something still breaks.

**Comment by shawntanzk** [comment]
happy to, but not sure what this QC does and what I should be looking out for

**Comment by matentzn** [comment]
Dont worry about the qc.. Just add a cross reference that would 100% break the rules, like a fishy reference to something that can only be in humans.

**Comment by shawntanzk** [comment]
@matentzn - can I remove the fake ZFA xref now? Happy to update this to latest branch and if it passes stick the check back in :D

**Comment by shawntanzk** [comment]
wwhatttt ok yeah, it failed when i last looked, must have been something else

**Comment by anitacaron** [comment]
Superseded by #2928

**Pull request closed without merging**
