### PR TITLE
fixes#2406-NTR-subiliac-lymph-node

### LINKED ISSUE #2406: NTR: subiliac lymph node
**Comment:** The following term is needed to indicate the origin of the tissues used establish cell lines annotated in Cellosaurus. Many thanks

**Preferred term label:** subiliac lymph node
**Synonyms**
sub-ilal lymph node
subiliac lymphocenter [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
precrural lymph node [https://www.mpi.govt.nz/dmsdocument/26111/direct]
prefemoral lymph node [https://www.mpi.govt.nz/dmsdocument/26111/direct]
**Definition** Lymph node of the abdominal wall  situated subcutaneously (embedded in fat) on the lateral and on the ventral side of the abdominal wall. [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
**Parent term** abdominal lymph node UBERON:0002507
**NOTE** This term is used in swine [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian] and other animals [https://www.imaios.com/en/vet-Anatomy/Vet-Anatomical-Part/Subiliac-lymph-nodes]. The subiliac lymphocenter includes in, swine, the subiliac lymph nodes only. In Sisson, S. and Grossman. J. D. (Anatomy of the Domestic Animals. 4th edition. Press of W. B.Saunders Co.. Philadel",hla. 1953.) they are called the prefemoral lymph nodes. The term "prefemoral" is considered by the authors as somewhat unfortunate since the lymph nodes drain largely the subcutaneous dorso-lateral lumbar area of the trunk. In fact, the subiliac lymph nodes appear to be rather closely associated with the common iliac lymphocenter. [https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=2350&context=iowastate_veterinarian]
**Your nano-attribution (ORCID)** 0000-0002-0819-0473

### PR DESCRIPTION
**Pull request by paulacalipho**
fixes #2406

### CODE REVIEW

**Comment by paulacalipho** [comment]
Hello @anitacaron I need to look for another reviewer, but I still would like to do a PR. Do you think I can keep it like this until I find someone?

**Review by bvarner-ebi — CHANGES_REQUESTED** [review]
Hi @paulacalipho, the additions in the PR do not reflect [the latest comment](https://github.com/obophenotype/uberon/issues/2406#issuecomment-1448081273) in the linked issue. 

Since the annotations in the comment are more broad and may apply across more species, it seems reasonable to update the definition / synonym to reflect it.

**Comment by paulacalipho** [comment]
Hi @bvarner-ebi yes, I will work on this asap and update the PR

**Comment by bvarner-ebi** [comment]
Regarding the definition proposed in the linked ticket, I suggest replacing the word "below" with the appropriate anatomical term (deep, posterior, inferior, etc).

**Pull request merged**
