### PR TITLE
2022-06-29 Release

### PR DESCRIPTION
**Pull request by shawntanzk**
Have not reviewed yet - will get to it tmr
Making this PR so the checks will run while I sleep :)

### CODE REVIEW

**Comment by anitacaron** [comment]
There's a new file called `src/ontology/--no-check`. I think this is from the `subsets/life-stages-composite.owl` that I fixed here https://github.com/obophenotype/uberon/commit/f8bf73386c04a9b64e9b7ee19028de6db315abd9#diff-3be1ed61d54d61e9cf41bb5bae5497d601ae65461d4253518955f003ed162037

**Comment by anitacaron** [comment]
And about the subsets, are you still not going to include them in the release?

**Comment by shawntanzk** [comment]
> There's a new file called `src/ontology/--no-check`. I think this is from the `subsets/life-stages-composite.owl` that I fixed here [f8bf733#diff-3be1ed61d54d61e9cf41bb5bae5497d601ae65461d4253518955f003ed162037](https://github.com/obophenotype/uberon/commit/f8bf73386c04a9b64e9b7ee19028de6db315abd9#diff-3be1ed61d54d61e9cf41bb5bae5497d601ae65461d4253518955f003ed162037)

Should we put that in gitignore? I thought that was intentional. 

> And about the subsets, are you still not going to include them in the release?

Not 100% sure, I don't deal with subsets so don't really know, need input from @matentzn

**Review by matentzn — CHANGES_REQUESTED** [review]
Remove (git rm -f!)

--no-check (this has been fixed since)
-- renal-minimal subset
-- life-stages-composite.obo (subset)

Add them all to .gitignore (@anitacaron dealt with them)

**Comment by shawntanzk** [comment]
> Remove (git rm -f!)

totally did not learn this from the last obo training :p 

> -- renal-minimal subset
> -- life-stages-composite.obo (subset)

From src/ontology/subsets/ or subsets/ or both?

**Comment by anitacaron** [comment]
They're already in .gitignore. I've deleted the files, no worries, @shawntanzk

**Comment by shawntanzk** [comment]
@anitacaron - the files are still in this branch though? What do I need to do for this release then? thanks :)

**Comment by anitacaron** [comment]
Yeah, I've created another PR for them. I'll run the release again.

**Comment by shawntanzk** [comment]
ah thanks :) I'll close this and delete the branch then

**Pull request closed without merging**
