### PR TITLE
Addresses #2920 NTR placental villous stroma

### LINKED ISSUE #2920: NTR: placental villous stroma
**Preferred term label:**
placental villous stroma

**Synonyms**

**Definition (free text, please give PubMed ID)**
PMID: 31512233
Palaiologou E, Etter O, Goggin P, Chatelet DS, Johnston DA, Lofthouse EM, Doherty R, Pearson-Farr J, Sengers BG, Torrens C, Cleal JK, Page AM, Lewis RM. Human placental villi contain stromal macrovesicles associated with networks of stellate cells. J Anat. 2020 Jan;236(1):132-141. doi: 10.1111/joa.13082. Epub 2019 Sep 11. PMID: 31512233; PMCID: PMC6904625.

**Definition from paper:** The placental villous stroma is a connective tissue layer that supports the fetal capillaries and villous trophoblast.

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
unclear if an appropriate parent exists currently

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

### PR DESCRIPTION
**Pull request by aleixpuigb**
Fixes #2920 NTR placental villous stroma

### CODE REVIEW

**Review by bvarner-ebi — COMMENTED** [review]
Defer to requester's review of content.

The text and logical definitions use the term "chorionic villus" while the label is 'placental villous stroma', which could potentially cause user confusion. Should the label be updated and / or synonym added?

**Comment by aleixpuigb** [comment]
> The text and logical definitions use the term "chorionic villus" while the label is 'placental villous stroma', which could potentially cause user confusion. Should the label be updated and / or synonym added?

@emquardokus I have seen "chorionic villous stroma" and "placental villous stroma" in the literature without a clear preference. Is there a reason for the term to be labeled "placental villous stroma"?

**Comment by emquardokus** [comment]
@aleixpuigb 
my original NTR had this paper and definition: I'm not sure why the definition you have uses chorionic villus?

Definition from paper: The placental villous stroma is a connective tissue layer that supports the fetal capillaries and villous trophoblast.

Definition (free text, please give PubMed ID)
PMID: 31512233
Palaiologou E, Etter O, Goggin P, Chatelet DS, Johnston DA, Lofthouse EM, Doherty R, Pearson-Farr J, Sengers BG, Torrens C, Cleal JK, Page AM, Lewis RM. Human placental villi contain stromal macrovesicles associated with networks of stellate cells. J Anat. 2020 Jan;236(1):132-141. doi: 10.1111/joa.13082. Epub 2019 Sep 11. PMID: 31512233; PMCID: PMC6904625.

**Comment by aleixpuigb** [comment]
Thank you for your answer.

The reason behind having "chorionic villus" in the definition is to align with the logical definition. What I can do is to include placental villus in brackets for clarification:

`A stroma that is part of a chorionic villus (placental villous). A placental villous stroma supports the fetal capillaries and villous trophoblast.`

**Review by zoependlington — APPROVED** [review]

**Pull request merged**
