### PR TITLE
update def for UBERON:0012424 brush border layer

### LINKED ISSUE #1715: UBERON:0012424 brush border layer
**Uberon term**
UBERON:0012424 brush border layer

**Suggested revision of textual definition**
Defined as "The microvilli-covered surface of simple cuboidal epithelium and simple columnar epithelium cells found in certain locations of the body. Found in small intestine and kidney"
Has related synonyms: brush border membrane, brush border
Please consider disambiguating from GO_0005903 brush border ("The dense covering of microvilli on the apical surface of a epithelial cells in tissues such as the intestine, kidney, and choroid plexus; the microvilli aid absorption by increasing the surface area of the cell." - there are 2 typos too). Presumably you want the anatomical term to represent a collection of brush border cell components. Thanks.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
and add comment
closes #1715

@paola-scibite not sure if this addresses your issue? Let me know. :)

### CODE REVIEW

**Comment by paola-scibite** [comment]
Hi @nicolevasilevsky ,
Thanks! The comment you added should help disambiguate. A couple of minor things please:
- [ ] The revised def reads "The microvilli-covered surface of simple cuboidal epithelium and simple columnar epithelium cells found in certain locations of the body; mainly in the small _an_ large intestines and kidneys." [Wikipedia:Brush_border] please correct "an" in "and"
- [ ] Should the Uberon term have a has_part relationship to the GO term?
- [ ] I'll notify GO of the typos in their def. Thanks!

**Comment by dosumis** [comment]
> Should the Uberon term have a has_part relationship to the GO term?

I think so.  Could merge this for release & add in separate PR if not time to do now.

**Review by dosumis — APPROVED** [review]

**Comment by dosumis** [comment]
Merging for release.  Please add has_part fo GO term separately

**Comment by paolaroncaglia** [comment]
> Merging for release. Please add has_part fo GO term separately

I'd leave the suggestions in https://github.com/obophenotype/uberon/pull/1721#issuecomment-759350110 to @nicolevasilevsky or other Uberon editors please, to avoid COIs on my part :-) 
Not urgent anyway!
Thanks.

**Pull request merged**
