### PR TITLE
adding anatomical lines for traits

### PR DESCRIPTION
**Pull request by megbalk**
Added the following anatomical lines:
- line from helix of ear to incisure of ear
- line from medial condyle of femur to head of femur
- line from medial condyle of femur to greater trochanter of femur
- line from trochlea of humerus to proximal head of humerus
- line from trochlea of humerus to ventral tubercle of humerus

### CODE REVIEW

**Comment by ramonawalls** [comment]
According to the error message, the CI check is failing because:

`./util/check-obo-for-standard-release.pl --xref-abbs GO.xrf_abbs --disable-multiply-labeled-edge --disable-valid-id-space --disable-isa-incomplete --disable-ascii-check --disable-has-definition --disable-bad-pmid --disable-ontology-declaration-check --disable-referenced-id-syntax-check --disable-owl-axiom-check --disable-is-symmetric-check uberon_edit.obo > uberon_edit.obo-gocheck.tmp && mv uberon_edit.obo-gocheck.tmp uberon_edit.obo-gocheck
 :: ERROR: definition-lacks-dbxref: UBERON:7500000
  :: ERROR: definition-lacks-dbxref: UBERON:7500001
  :: ERROR: definition-lacks-dbxref: UBERON:7500003
  :: ERROR: definition-lacks-dbxref: UBERON:7500004
  :: ERROR: definition-lacks-dbxref: UBERON:7500005`

Are dbxrefs required for every term? These are new terms so there are no dbxrefs.

**Comment by matentzn** [comment]
Looking through uberon, it seems that many people add their orcids as dbxrefs.. That it what I recently recommended [here](https://github.com/obophenotype/uberon/pull/1558#issuecomment-581583212).. Not sure that should be best practice, but why not. New term, so you are the reference :)

**Comment by ramonawalls** [comment]
> Looking through uberon, it seems that many people add their orcids as dbxrefs.. That it what I recently recommended [here](https://github.com/obophenotype/uberon/pull/1558#issuecomment-581583212).. Not sure that should be best practice, but why not. New term, so you are the reference :)

Or one could change the CI check. :)

**Comment by megbalk** [comment]
re: reference, I have the name of the reference (IAO: 0000119). Does that not suffice?

**Comment by ramonawalls** [comment]
Also, normally I add my ORCID  to terms as a value to dc:creator or dc:contributor.

**Comment by ramonawalls** [comment]
@megbalk 750002-750005 do not have any annotation properties. Please add the labels, definitions, and references for these. Please also add your ORCID to all terms as an annotation property using the property `database_cross_reference`.

Also check the labels for the terms to be sure if you want to use "of" of "from". I think in these cases, "from" is more appropriate.

**Comment by ramonawalls** [comment]
This branch now has a bunch of edits on it that were not done by @megbalk. Has anyone from @obophenotype/uberon-curators been somehow mysteriously editing this file without it being tracked? Is that even possible. @megbalk perhaps you accidentally committed from the wrong branch?

**Comment by megbalk** [comment]
I dont think so as it's from the fovt-1 branch.

**Comment by balhoff** [comment]
@ramonawalls are the changes you're wondering about the various label changes in OBO comments? If so that tends to happen if an import is updated in between when the main file was saved and when you make other edits. CL changed some term labels.

**Comment by ramonawalls** [comment]
Ah! Yes, I think that could have caused it. Thanks, Jim.
------------------------------------------------------
Ramona L. Walls, Ph.D.
Assistant Research Professor, Bio5 Institute, University of Arizona
Senior Scientific Analyst, CyVerse, University of Arizona
Part-time artist

**Comment by megbalk** [comment]
going to close this branch and redo - there was an issue with the numbering.

**Pull request closed without merging**
