### PR TITLE
adding temporal line

### PR DESCRIPTION
**Pull request by helenamachado**
address #2880

### CODE REVIEW

**Comment by megbalk** [comment]
@nicolevasilevsky what do you think about ridge having subclass "connects"? I am unsure how to think through that.

**Comment by nicolevasilevsky** [comment]
A few things:
1. The diff is really huge because of the new Protege version. But I thought someone already normalized this and we shouldn't be seeing these big diffs anymore. @helenamachado did you pull from master before you did these edits? I just did 'update from master' but I don't think that helped. (So I'm not sure why the diff is like this)
2. @helenamachado - if you want this PR to close a ticket when it is merged, you should write `fix #2882` and `fix #2880` (or address if you just want to link them but not close when the PR is merged)
3. @megbalk I'm not sure I understand your question. There is already a relation/object property called connects. I'm not sure connect makes sense as a class - do you intend it to be an actual anatomical entity?

**Review by megbalk — APPROVED** [review]

**Comment by megbalk** [comment]
@helenamachado please change the comment from "addresses" to "fix" and feel free to merge!

**Comment by megbalk** [comment]
@helenamachado please change the comment from "addresses" to "fix" and feel free to merge!

**Comment by helenamachado** [comment]
> 

1. I didn't, I've pulled directly from 2880 branch. Should I have done it from the master? Also, I just realized I haven't updated Protege yet when I did the edits, could that be it?
2. I see, sorry for the confusion!

**Comment by helenamachado** [comment]
fix #2882 
fix #2880

**Comment by anitacaron** [comment]
Please, when not using the new Protégé, run `sh run.sh make normalize_src` before commit. @helenamachado, ping me if you need help.

**Pull request merged**
