### PR TITLE
added euryon, supraorbital foramen, supraorbitale and entorbitale

### PR DESCRIPTION
**Pull request by helenamachado**
issue #2889

### CODE REVIEW

**Comment by anitacaron** [comment]
@helenamachado, please [download the new Protégé 5.6](https://protege.stanford.edu/software.php#desktop-protege) to suggest changes into Uberon ontology.

**Review by anitacaron — CHANGES_REQUESTED** [review]
Update the branch by opening it with new Protégé 5.6 or running `sh run.sh make normalization_src`.

**Comment by anitacaron** [comment]
Hi @megbalk, if you don't have docker and normally run scripts to be able to run `sh run.sh make normalization_src`, you need to open `uberon-edit.obo` from her branch using the new Protégé, do a change to it and save it, then commit it again here.

**Comment by megbalk** [comment]
@anitacaron I do have docker, so I can go to src/ontology and run `sh run.sh make normalization_src` correct?

**Comment by megbalk** [comment]
@anitacaron I get the following error: make: `*** No rule to make target 'normalization_src'.  Stop.`

**Comment by megbalk** [comment]
I didn't get any errors, but I also didn't get changes to commit...

```
uberon.Makefile:199: warning: overriding recipe for target 'ext.owl'
Makefile:778: warning: ignoring old recipe for target 'ext.owl'
uberon.Makefile:215: warning: overriding recipe for target 'uberon.owl'
Makefile:711: warning: ignoring old recipe for target 'uberon.owl'
uberon.Makefile:219: warning: overriding recipe for target 'uberon.obo'
Makefile:715: warning: ignoring old recipe for target 'uberon.obo'
uberon.Makefile:236: warning: overriding recipe for target 'basic.owl'
Makefile:781: warning: ignoring old recipe for target 'basic.owl'
uberon.Makefile:239: warning: overriding recipe for target 'basic.obo'
Makefile:677: warning: ignoring old recipe for target 'basic.obo'
uberon.Makefile:1264: warning: overriding recipe for target 'composite-metazoan.owl'
Makefile:784: warning: ignoring old recipe for target 'composite-metazoan.owl'
uberon.Makefile:1269: warning: overriding recipe for target 'composite-vertebrate.owl'
Makefile:790: warning: ignoring old recipe for target 'composite-vertebrate.owl'
uberon.Makefile:1282: warning: overriding recipe for target 'composite-metazoan-basic.owl'
Makefile:787: warning: ignoring old recipe for target 'composite-metazoan-basic.owl'
uberon.Makefile:1286: warning: overriding recipe for target 'composite-vertebrate-basic.owl'
Makefile:793: warning: ignoring old recipe for target 'composite-vertebrate-basic.owl'
robot --catalog catalog-v001.xml convert -i uberon-edit.obo -f obo --check false -o tmp/normalise && mv tmp/normalise uberon-edit.obo
```

**Review by anitacaron — DISMISSED** [review]

**Review by megbalk — APPROVED** [review]

**Pull request merged**
